### ISSUE TITLE
bug v202310160022 Can't paste into cell

### ISSUE THREAD

**Issue by hackerhui** [siyuan-note/siyuan#9441] opened 2023-10-16 12:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

step 1: create table
step 2:Copy any text
step 3:Right click on cell and paste

### Expected result

The text is not pasted into the cell, but is still a separate block.
v202310141200  is normal

### Version environment

```markdown
- Version: v202310160022
- Operating System: 
- Browser (if used):
```

### Log file

none

**Comment by zxhd863943427** [comment] 2023-10-16 14:46
Can you provide a demo of a video or GIF? I can't reproduce it here.

**Comment by 88250** [comment] 2023-10-16 15:59
Duplicate of https://github.com/siyuan-note/siyuan/issues/9438

**Closed by 88250** 2023-10-16 15:59 UTC
