### ISSUE TITLE
docker搭建的siyuan,升级到最新版本后，打开web页面，都是空白的。

### ISSUE THREAD

**Issue by bear0328** [siyuan-note/siyuan#11272] opened 2024-05-06 10:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

docker搭建的siyuan,升级到最新版本后，打开web页面，都是空白的。

### Expected result

青椒是否可以解决

### Version environment

```markdown
- Version: 3.0.12
- Operating System: Windows
- Browser (if used): Chrome
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/15219340/siyuan.log)

**Comment by TCOTC** [comment] 2024-05-06 10:36
Duplicate of #11195

**Closed** 2024-05-06 13:31 UTC
