### ISSUE TITLE
"Reveal in Finder" hanging for a long time on macOS

### ISSUE THREAD

**Issue by LoneFireBlossom** [siyuan-note/siyuan#9221] opened 2023-09-18 13:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在Finder（文件管理器）中显示要等一大阵子。
<img width="396" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/ad21c7d4-b5bc-436d-9565-a242d50b58f9">

https://obsidian.md/changelog/

Obsidian之前也有这个bug然后修复了。
<img width="940" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/60279dd4-aa86-40e4-b52d-4c59624c5cfc">

### Expected result

*

### Version environment

```markdown
- Version: 2.10.5
- Operating System: macOS 13.5.2
- Browser (if used):
```

### Log file

这log里也没有啊，我刚刚9:24又按了一次log导出，log里最下面是9:17的

**Comment by 88250** [comment] 2023-09-19 01:09
Duplicate of https://github.com/siyuan-note/siyuan/issues/8705

**Closed by 88250** 2023-09-19 01:09 UTC

**Comment by LoneFireBlossom** [comment] 2023-09-19 01:15
我错了。交issue交多了，烦了不想查历史直接都打了勾
