### ISSUE TITLE
The local graph triggered by `ALT+8` won't change according to active file.

### ISSUE THREAD

**Issue by Lemoners** [siyuan-note/siyuan#1944] opened 2021-04-02 03:27 UTC
### Describe the problem

The local graph triggered by `ALT+8` **won't change** as I click on different files.

### Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/39124095/113377184-26d0bb80-93a6-11eb-8db4-b6d07e530332.png)

Clearly the local graph (on the upper right corner) is for **a different file** rather than the file I'm editing right now.

### Version environment

* Version: 1.1.6
* Operating system: Windows

**Comment by 88250** [comment] 2021-04-03 09:45
Hello, I can't reproduce it on v1.1.7, please upgrade and try again, thanks.

I closed it first, if you still have any questions, please continue to post, thank you.

**Closed by 88250** 2021-04-03 09:45 UTC
