### ISSUE TITLE
Please enter the title of the feature request

### ISSUE THREAD

**Issue by wangzhongqi1995** [siyuan-note/siyuan#11405] opened 2024-05-15 02:38 UTC
### In what scenarios do you need this feature?

希望数据库筛选功能可以支持筛选同一个字段

### Describe the optimal solution

<img width="248" alt="image" src="https://github.com/siyuan-note/siyuan/assets/47977537/0862d31c-81ff-4d20-8f18-3ec0b2c3241e">
如图所示，我希望数据库的当前表格可以筛选状态为未收货和为空的字段，因为我希望在录入的时候可以当前表格录入，而在不存在筛选的表格中录入，当前表格查看。

**Comment by 88250** [comment] 2024-05-15 02:48
Duplicate of https://github.com/siyuan-note/siyuan/issues/10550

**Closed by 88250** 2024-05-15 02:48 UTC
