### ISSUE TITLE
数据库可编辑区域双击无法进入编辑状态

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#10222] opened 2024-01-20 00:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

详细情况有录屏发给D大了

### Expected result

进行修复

### Version environment

```markdown
- Version: 2.12.3
- Operating System: Windows 11
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/13995949/siyuan.log)

**Comment by 88250** [comment] 2024-01-20 01:05
Duplicate of https://github.com/siyuan-note/siyuan/issues/10200

**Closed by 88250** 2024-01-20 01:05 UTC
