### ISSUE TITLE
ctrl+x 剪切快捷键会把整个块的内容删除

### ISSUE THREAD

**Issue by mzcxiaohuanxiong** [siyuan-note/siyuan#9326] opened 2023-10-01 06:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

ctrl+x 剪切快捷键会把整个块的内容删除，鼠标右键剪切不会

### Expected result

恢复正常剪切快捷键功能

### Version environment

```markdown
- Version: v2.10.7
- Operating System: win10
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/12776552/siyuan.log)

**Comment by 88250** [comment] 2023-10-01 07:58
Duplicate of https://github.com/siyuan-note/siyuan/issues/9283

**Closed by 88250** 2023-10-01 07:58 UTC
