### ISSUE TITLE
Autofill database relation column when adding new row on a filtered view

### ISSUE THREAD

**Issue by cracra-droid** [siyuan-note/siyuan#12836] opened 2024-10-19 09:50 UTC
### In what scenarios do you need this feature?

I believe this feature is crucial to efficiently manage databases related to each other. 

An exemple would be adding a task to a project from a filtered view inside the project's note. Without this feature, new row automatically gets filtered and doesn't appear at all. For now, a workaround is needed to add a new row to the tasks database, then link it back to the project.

### Describe the optimal solution

Notion-like autofill on relation columns when adding a row from a filtered view.

https://github.com/user-attachments/assets/a1335aed-9313-4827-8cb1-38a2d1b9ec2a

### Other information

I believe it is related to #12000 as it would require implementing dynamic filtering on relation column first, I suppose.

**Comment by TCOTC** [comment] 2024-10-19 10:01
Duplicate of #11966

**Closed** 2024-10-19 10:03 UTC

**Comment by cracra-droid** [comment] 2024-10-19 10:23
> Duplicate of #11966

Sorry, I've looked at the other issues but didn't see this one !
Do you have any idea about the release timeline of this feature?

Thank you so much for your great work! 👏

**Comment by 88250** [comment] 2024-10-19 10:26
Sorry, there is no definite plan yet, for now you can consider using drop-down fill to manually copy.

**Comment by cracra-droid** [comment] 2024-10-19 10:51
Thanks! I'll be waiting for it :)
