### ISSUE TITLE
Error deleting a paragraph

### ISSUE THREAD

**Issue by taozina0587** [siyuan-note/siyuan#6242] opened 2022-10-17 14:35 UTC
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

In SOME cases when typing text, I press "double SHIFT+ENTER" to add a distance between the lines.
Sometimes I want to undo it! I go to the beginning of the line and press "backspace". However, the entire paragraph is deleted.

I record my screen...

![11](https://user-images.githubusercontent.com/90691302/196204594-8d44d7af-4e6b-4ab1-9687-48e2bfd85ccf.gif)

Below is my text file (.sy.zip) to check my problem:

[problem.sy.zip](https://github.com/siyuan-note/siyuan/files/9801533/problem.sy.zip)

### 期待的结果 Expected result

By pressing the "backspace" key, the paragraph goes back to the end of the previous line.

### 版本环境 Version environment

```markdown
- Version: 2.4.1
- Operating System: Win10
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9801550/siyuan.log)

**Comment by 88250** [comment] 2022-10-18 01:06
Hello, I can't reproduce it: 

![issue](https://user-images.githubusercontent.com/873584/196311424-5d7fa007-4675-4a99-b007-0b8152438a9e.gif)

**Comment by taozina0587** [comment] 2022-10-18 01:30
Hello. I think you didn't press 2x "shift+enter" at the beginning of the paragraph. I don't see the symbol that appears when hovering.

**Comment by taozina0587** [comment] 2022-10-18 01:31
One moment...

**Comment by taozina0587** [comment] 2022-10-18 01:34
I also tested this file I sent you, but the error is gone!
So the problem is in the block set?

**Comment by 88250** [comment] 2022-10-18 01:36
Not sure yet.

**Comment by taozina0587** [comment] 2022-10-18 01:41
I understand the problem... I study on two computers: one at my work and one at home. I'm always exporting and importing the data. From what I understand, the error is when exporting and importing the DATA there in the settings menu. But when exporting via "sy.zip" the file is normal.

**Comment by taozina0587** [comment] 2022-10-18 01:51
https://drive.google.com/drive/folders/1_5l_y4fLmp3VqDX_xbwiZj0ID_KzNrTt?usp=sharing

**Comment by 88250** [comment] 2022-10-18 02:21
![issue](https://user-images.githubusercontent.com/873584/196320310-6b720318-0ae4-47ee-97cd-75182486bf10.gif)

**Comment by taozina0587** [comment] 2022-10-18 02:25
So I do not know. I tested it again now with this google drive file. The bug continues. I use windows 10 at work and linux at home.

**Comment by 88250** [comment] 2022-10-18 02:30
I found some error logs in siyuan.log you uploaded, please do not place workspace in OneDrive.

**Comment by 88250** [comment] 2022-10-18 02:33
![issue](https://user-images.githubusercontent.com/873584/196321978-db9161e1-5e8d-46d4-adc4-1439cfb576e6.gif)

**Comment by taozina0587** [comment] 2022-10-18 02:34
Ok. I tried it now also on my iPad. The bug continues. I really do not understand. thank you very much for the one drive tip

**Comment by 88250** [comment] 2022-10-18 03:40
We have closed it first, if there are more additions in the future, please feel free to post, thank you.

**Closed by 88250** 2022-10-18 03:40 UTC

**Comment by taozina0587** [comment] 2022-10-18 09:16
@88250 I record my screen. 

![123](https://user-images.githubusercontent.com/90691302/196389643-4a50931b-e871-4e03-b53f-5ac9f4f28b56.gif)

**Comment by taozina0587** [comment] 2022-10-18 09:37
@88250 Hi friend, look this...

![1111](https://user-images.githubusercontent.com/90691302/196394539-8f3cda26-8188-4691-ba9e-04a806f858d5.gif)

**Comment by 88250** [comment] 2022-10-18 09:57
A paragraph with newline `\n` will break it into multiple lines, we called it as "Soft line breaks", it render as `<br>` in SiYuan, this is the correct behavior as expected.

**Comment by taozina0587** [comment] 2022-10-18 10:31
@88250 Thank you friend. This error is happening since version 2.2 with me. I'm going back to version 2.1.14 which is working properly for my use.
