### ISSUE TITLE
软件升级手动覆盖安装软件不能继承任务栏锁定

### ISSUE THREAD

**Issue by chenshinshi** [siyuan-note/siyuan#8862] opened 2023-07-31 05:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

似乎是因为新安装的和之前的算作两个版本两个软件，wox 的搜索置顶也会失效。
https://ld246.com/article/1690767318109
非win商店版本。
评论区还有人说以前某个版本是可以正常继承的。

### Expected result

希望能同市面其他软件一样正常继承。

### Version environment

```markdown
- Version: 2.9.7
- Operating System: win
- Browser (if used):
```

### Log file

无需

**Comment by 88250** [comment] 2023-07-31 11:59
Duplicate of https://github.com/siyuan-note/siyuan/issues/3773

**Closed by 88250** 2023-07-31 11:59 UTC
