### ISSUE TITLE
v3.0.15 版本不能用# 号来快速打标签

### ISSUE THREAD

**Issue by EdwardTan666** [siyuan-note/siyuan#11536] opened 2024-05-26 08:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

v3.0.15 版本不能用# 号来快速打标签，以前可以的

### Expected result

修复这个问题

### Version environment

```markdown
- Version: v3.0.15
- Operating System: Windows 11
- Browser (if used):
```

### Log file

没有

**Comment by 88250** [comment] 2024-05-26 08:52
Duplicate of https://github.com/siyuan-note/siyuan/issues/11494

**Closed by 88250** 2024-05-26 08:52 UTC
