### ISSUE TITLE
Update Firefox Extension

### ISSUE THREAD

**Issue by UsmanTechJive** [siyuan-note/siyuan#13069] opened 2024-11-06 19:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

The Firefox Siyuan extension is not updated, while the Chrome extension is updated. This is not a bug, but an issue.

Firefox:

![image](https://github.com/user-attachments/assets/6982d3af-daa4-4974-904c-0b6ed9e6dc95)

Chrome:

![image](https://github.com/user-attachments/assets/3672fb3a-3dfe-4c62-83e5-64b37944840d)

Zen Browser, which is based on Firefox, is now gaining popularity. I'm using it, and I just noticed that the extension is not updated there.

This is how it looks in Zen Browser:

![image](https://github.com/user-attachments/assets/6b585657-b327-496e-b2ea-aa4954ee4a96)

### Expected result

-

### Version environment

```markdown
- Version: 3.1.11
- Operating System: 
- Browser (if used):
```

### Log file

-

**Comment by 88250** [comment] 2024-11-07 05:31
Duplicate of #4057

**Closed by 88250** 2024-11-07 05:31 UTC

**Comment by Littleweisheit** [comment] 2024-11-08 07:43
@UsmanTechJive set access code in “about” page.
![图片](https://github.com/user-attachments/assets/466c81bc-b3b8-4918-ae1f-850732b71dac)

**Comment by UsmanTechJive** [comment] 2024-11-08 10:36
> @UsmanTechJive set access code in “about” page.will worl in firefox. ![图片](https://private-user-images.githubusercontent.com/11383988/384271986-466c81bc-b3b8-4918-ae1f-850732b71dac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNjIzOTAsIm5iZiI6MTczMTA2MjA5MCwicGF0aCI6Ii8xMTM4Mzk4OC8zODQyNzE5ODYtNDY2YzgxYmMtYjNiOC00OTE4LWFlMWYtODUwNzMyYjcxZGFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDEwMzQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlZWE0Yjg4MjcwZDE2NGYyMGU4NDcyYzk3ZGZlODQ3MjY0MzM3NDM4MWEzMDc0ZTgxOTdiMmVkYjJmNzcwNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FNOj3y-vKJiyH9FButPtoXxTe2kAFhVlUkSgkL2AiDI)

Tested, it worked. Thanks!

**Comment by Littleweisheit** [comment] 2024-11-08 11:22
> > @UsmanTechJive set access code in “about” page.will worl in firefox. ![图片](https://private-user-images.githubusercontent.com/11383988/384271986-466c81bc-b3b8-4918-ae1f-850732b71dac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNjIzOTAsIm5iZiI6MTczMTA2MjA5MCwicGF0aCI6Ii8xMTM4Mzk4OC8zODQyNzE5ODYtNDY2YzgxYmMtYjNiOC00OTE4LWFlMWYtODUwNzMyYjcxZGFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDEwMzQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlZWE0Yjg4MjcwZDE2NGYyMGU4NDcyYzk3ZGZlODQ3MjY0MzM3NDM4MWEzMDc0ZTgxOTdiMmVkYjJmNzcwNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FNOj3y-vKJiyH9FButPtoXxTe2kAFhVlUkSgkL2AiDI)
> 
> Tested, it worked. Thanks!

universal web clipper also work.you can try it.
