### ISSUE TITLE
Online check always uses the same fixed url (baidu.com).

### ISSUE THREAD

**Issue by eulores** [siyuan-note/siyuan#7835] opened 2023-03-30 18:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

I constantly receive this error message:
_The network connectivity verification of the cloud storage service provider is abnormal, please check the network configuration._
implying that my cloud storage service is not reachable.

Yet, verification via the browser shows no connectivity issues.

As it turns out, the online verification is done against `baidu.com`, and the one second timeout is too short and triggers this error message.

### Expected result

I am expecting to continue using the cloud storage service with no errors.

### Version environment

```markdown
- Version: 2.8.2
- Operating System: Windows
- Browser (if used): n/a
```

### Log file

n/a

### More information

The function `isOnline` in the file `kernel/util/net.go` ignores the argument `checkURL` and instead uses `baidu.com` with a very short timeout.

Please also consider including `google.com` as another of the online checking default URLs, thanks.

**Comment by 88250** [comment] 2023-03-31 01:05
Duplicate of https://github.com/siyuan-note/siyuan/issues/7831

**Closed by 88250** 2023-03-31 01:05 UTC
