### ISSUE TITLE
Feature Request: Add Pinned/Favorites Section to Document Tree for Quick Access at Top

### ISSUE THREAD

**Issue by MrIntellectX** [siyuan-note/siyuan#10776] opened 2024-03-27 20:18 UTC
### In what scenarios do you need this feature?

Currently, SiYuan lacks a feature found in other productivity and note-taking applications like Notion and Capacities, the ability to pin or favorite documents for quick access at the top of the doc tree. This functionality is incredibly useful for users who frequently access specific documents and would benefit from having them readily available.

![SiYuan_IvqE5DUoU7](https://github.com/siyuan-note/siyuan/assets/36538038/4f173e29-0903-43a0-b76e-c98bf6f26a4f)

### Describe the optimal solution

The optimal solution would involve the implementation of a pinned or favorites section at the top of the document tree. By default, if a user hasn't pinned any documents, the document tree would remain as it is currently. However, once a user pins a document, this section would become visible at the top of the tree, providing quick and easy access to selected documents.

Notion:
![Notion_ZGCQQB5JIz](https://github.com/siyuan-note/siyuan/assets/36538038/2eeb8992-737b-4a2f-b5d2-ae6cbc3c3828)

Capacities:
![Arc_ttaxUQkUMm](https://github.com/siyuan-note/siyuan/assets/36538038/49cc7163-11b3-4a2e-82bf-3798247cb881)

### Describe the candidate solution

This feature could be implemented with a simple pin icon next to each document or by allowing users to drag and drop documents into the pinned section.

**Comment by 88250** [comment] 2024-03-28 00:24
Duplicate of https://github.com/siyuan-note/siyuan/issues/9466

Thanks.

**Closed by 88250** 2024-03-28 00:24 UTC
