### ISSUE TITLE
批量替换对文档数量有限制

### ISSUE THREAD

**Issue by HopeLHP** [siyuan-note/siyuan#8547] opened 2023-06-15 07:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在文件夹下替换文本，搜索结果文档数量和关键词数量都是65个，替换文本后发现只修改了32个文档，因此完成全部需要进行3次替换。

### Expected result

一次性批量对全部搜索结果进行替换

### Version environment

```markdown
- Version: 2.9.1
- Operating System: MacOS 13.4
- Browser (if used):
```

### Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/11754320/system-log.zip)

**Comment by 88250** [comment] 2023-06-15 07:51
Duplicate of https://github.com/siyuan-note/siyuan/issues/8265

**Closed by 88250** 2023-06-15 07:51 UTC
