### ISSUE TITLE
Docker 部署 v3.0.12 desktop桌面浏览器无法访问，mobile移动端可访问( The Docker deployment of v3.0.12 desktop browser is inaccessible, while the mobile version is accessible.)

### ISSUE THREAD

**Issue by haoranwei** [siyuan-note/siyuan#11265] opened 2024-05-05 18:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Docker 部署 [v3.0.12](https://hub.docker.com/layers/b3log/siyuan/v3.0.12/images/sha256-e4739a142279317ddc36fb30d7185457bf71ae82541011affbf16679d20445f5?context=explore)  Docker Deploy [v3.0.12](https://hub.docker.com/layers/b3log/siyuan/v3.0.12/images/sha256-e4739a142279317ddc36fb30d7185457bf71ae82541011affbf16679d20445f5?context=explore) 

电脑浏览器访问，鉴权后一直卡在如下图所示页面
The computer browser access is stuck on the page as shown in the following image after authentication.

![image](https://github.com/siyuan-note/siyuan/assets/111106685/2080ac8c-73a3-4c70-99ac-fe1e5391087a)

但是，移动端访问正常，即：我将网站`/stage/build/desktop/`切换成`/stage/build/mobile`就能进入页面
However, accessing it from a mobile device is normal. In other words, when I switch the website from `/stage/build/desktop/` to `/stage/build/mobile`, I can access the page.

我将docker镜像降级到了[v3.0.5](https://hub.docker.com/layers/b3log/siyuan/v3.0.5/images/sha256-eebeeb33c5bd7e1527733045ff9add75ec5644e61a2a70165e83bca4b3671f8d?context=explore)，重新部署，desktop端就可以正常访问了。因此我认为此bug存在于最新版本中
I downgraded the Docker image to [v3.0.5](https://hub.docker.com/layers/b3log/siyuan/v3.0.5/images/sha256-eebeeb33c5bd7e1527733045ff9add75ec5644e61a2a70165e83bca4b3671f8d?context=explore) and redeployed it. After this, the desktop version can be accessed normally. Therefore, I believe that this bug exists in the latest version.

### Expected result

期望最新版本[v3.0.12](https://hub.docker.com/layers/b3log/siyuan/v3.0.12/images/sha256-e4739a142279317ddc36fb30d7185457bf71ae82541011affbf16679d20445f5?context=explore)  的desktop端能正常访问，如下图所示
The desktop version should be accessible normally with the latest version [v3.0.12](https://hub.docker.com/layers/b3log/siyuan/v3.0.12/images/sha256-e4739a142279317ddc36fb30d7185457bf71ae82541011affbf16679d20445f5?context=explore) deployed via Docker, as shown in the following image.

![image](https://github.com/siyuan-note/siyuan/assets/111106685/4a42ddcb-83e6-4fe3-8f85-f4560dc1c9f4)

### Version environment

```markdown
- Version: [v3.0.12](https://hub.docker.com/layers/b3log/siyuan/v3.0.12/images/sha256-e4739a142279317ddc36fb30d7185457bf71ae82541011affbf16679d20445f5?context=explore)
- Operating System: Centos 7
- Browser (if used): Chrome,Edge
```

### Log file

```bash
I 2024/05/06 00:37:22 working.go:146: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2024/05/06 00:37:22 runtime.go:74: kernel is booting:
    * ver [3.0.12]
    * arch [amd64]
    * os [alpine]
    * pid [1]
    * runtime mode [prod]
    * working directory [/opt/siyuan]
    * read only [false]
    * container [docker]
    * database [ver=20220501]
    * workspace directory [/siyuan/workspace/]
D 2024/05/06 00:37:26 conf.go:165: check device locale failed [detect: not detected], using default language [en_US]
I 2024/05/06 00:37:26 runtime.go:123: use network proxy [system]
I 2024/05/06 00:37:26 serve.go:116: kernel [pid=1] http server [0.0.0.0:6806] is booting
I 2024/05/06 00:37:28 database.go:90: the database structure is changed, rebuilding database...
I 2024/05/06 00:37:28 database.go:110: reinitialized database [/siyuan/workspace/temp/siyuan.db]
I 2024/05/06 00:37:28 conf.go:848: database size [4.1 kB], tree/block count [0/0]
I 2024/05/06 00:37:28 working.go:192: kernel booted
I 2024/05/06 00:37:28 box.go:76: auto stat [trees=0, blocks=0, dataSize=36.87 kB, assetsSize=0 B]
I 2024/05/06 00:37:36 session.go:116: auth success [ip=182.118.236.55:31831]
I 2024/05/06 00:37:38 serve.go:208: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36]
I 2024/05/06 00:38:26 serve.go:208: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36]
I 2024/05/06 00:38:39 serve.go:208: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36]
I 2024/05/06 00:39:24 session.go:116: auth success [ip=182.118.236.55:8189]
I 2024/05/06 00:39:24 serve.go:208: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0]
I 2024/05/06 00:40:50 serve.go:208: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36]
I 2024/05/06 00:42:27 process.go:36: received os signal [terminated], exit kernel process now
I 2024/05/06 00:42:27 conf.go:585: exiting kernel [force=false, setCurrentWorkspace=true, execInstallPkg=1]
I 2024/05/06 00:42:27 database.go:1280: closed database
I 2024/05/06 00:42:27 conf.go:1012: cleared workspace temp
I 2024/05/06 00:42:27 sync.go:712: sync websocket closed
I 2024/05/06 00:42:34 working.go:146: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2024/05/06 00:42:34 runtime.go:74: kernel is booting:
    * ver [3.0.12]
    * arch [amd64]
    * os [alpine]
    * pid [1]
    * runtime mode [prod]
    * working directory [/opt/siyuan]
    * read only [false]
    * container [docker]
    * database [ver=20220501]
    * workspace directory [/siyuan/workspace/]
I 2024/05/06 00:42:34 conf.go:124: loaded conf [/siyuan/workspace/conf/conf.json]
I 2024/05/06 00:42:34 runtime.go:123: use network proxy [system]
I 2024/05/06 00:42:34 serve.go:116: kernel [pid=1] http server [0.0.0.0:6806] is booting
I 2024/05/06 00:42:34 blocktree.go:509: read block tree [0 B] to [/siyuan/workspace/temp/blocktree], elapsed [0.00s]
I 2024/05/06 00:42:34 conf.go:848: database size [94.21 kB], tree/block count [0/0]
I 2024/05/06 00:42:34 working.go:192: kernel booted
I 2024/05/06 00:42:34 box.go:76: auto stat [trees=0, blocks=0, dataSize=36.87 kB, assetsSize=0 B]
I 2024/05/06 00:43:42 session.go:116: auth success [ip=182.118.236.55:28386]
I 2024/05/06 00:43:42 serve.go:208: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36]
I 2024/05/06 00:45:54 session.go:116: auth success [ip=182.118.236.55:6399]
I 2024/05/06 00:45:54 serve.go:208: serving [/] for user-agent [Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Mobile Safari/537.36 EdgA/123.0.0.0]
W 2024/05/06 00:46:09 file.go:361: build docs [9] elapsed [1102ms]
I 2024/05/06 00:46:10 index.go:207: rebuilt database for notebook [20210808180117-6v0mkxr] in [0.80s], tree [count=66, size=1.16 MB]
I 2024/05/06 00:46:10 index.go:279: resolved refs [31] in [41ms]
W 2024/05/06 00:46:24 blocktree.go:572: save block tree [size=633.5 kB] to [/siyuan/workspace/temp/blocktree], elapsed [9.46s]
E 2024/05/06 00:46:44 rhy.go:48: get version info failed: Get "https://siyuan-sync.b3logfile.com/apis/siyuan/version?ver=3.0.12": net/http: TLS handshake timeout
I 2024/05/06 00:48:48 mount.go:145: removed box [20210808180117-6v0mkxr]
W 2024/05/06 00:48:58 blocktree.go:572: save block tree [size=256 B] to [/siyuan/workspace/temp/blocktree], elapsed [9.34s]
I 2024/05/06 00:49:21 session.go:116: auth success [ip=182.118.236.55:23235]
I 2024/05/06 00:49:21 serve.go:208: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36]
I 2024/05/06 00:50:25 session.go:116: auth success [ip=182.118.236.55:28163]
I 2024/05/06 00:51:50 session.go:116: auth success [ip=182.118.236.55:34396]
I 2024/05/06 00:51:50 serve.go:208: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0]
W 2024/05/06 00:52:34 history.go:567: history dir [/siyuan/workspace/history] not exist
W 2024/05/06 01:02:34 history.go:567: history dir [/siyuan/workspace/history] not exist
I 2024/05/06 01:02:57 session.go:116: auth success [ip=182.118.236.55]
I 2024/05/06 01:02:57 serve.go:208: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0]
I 2024/05/06 01:03:37 serve.go:208: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0]
I 2024/05/06 01:03:58 serve.go:208: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0]
I 2024/05/06 01:04:40 serve.go:208: serving [/] for user-agent [Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Mobile Safari/537.36 Edg/122.0.0.0]
I 2024/05/06 01:05:24 database.go:110: reinitialized database [/siyuan/workspace/temp/siyuan.db]
I 2024/05/06 01:05:24 index.go:279: resolved refs [0] in [0ms]
I 2024/05/06 01:05:41 mount.go:65: created box [20240506010541-0r8cgoi]
I 2024/05/06 01:05:46 index.go:207: rebuilt database for notebook [20240506010541-0r8cgoi] in [5.06s], tree [count=0, size=0 B]
I 2024/05/06 01:05:46 index.go:279: resolved refs [0] in [0ms]
I 2024/05/06 01:07:19 file.go:1628: removed doc [20240506010541-0r8cgoi/20240506010539-10m3l61.sy]
I 2024/05/06 01:08:52 serve.go:208: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0]
I 2024/05/06 01:11:00 serve.go:208: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0]
I 2024/05/06 01:11:25 session.go:116: auth success [ip=182.118.236.55]
I 2024/05/06 01:14:55 serve.go:208: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0]
I 2024/05/06 01:19:19 session.go:116: auth success [ip=182.118.236.55]
I 2024/05/06 01:19:19 serve.go:208: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0]
I 2024/05/06 01:21:26 process.go:36: received os signal [terminated], exit kernel process now
I 2024/05/06 01:21:26 conf.go:585: exiting kernel [force=false, setCurrentWorkspace=true, execInstallPkg=1]
I 2024/05/06 01:21:26 database.go:1280: closed database
I 2024/05/06 01:21:26 conf.go:1012: cleared workspace temp
I 2024/05/06 01:21:27 sync.go:712: sync websocket closed
I 2024/05/06 01:28:04 working.go:146: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2024/05/06 01:28:04 runtime.go:74: kernel is booting:
    * ver [3.0.5]
    * arch [amd64]
    * os [alpine]
    * pid [1]
    * runtime mode [prod]
    * working directory [/opt/siyuan]
    * read only [false]
    * container [docker]
    * database [ver=20220501]
    * workspace directory [/siyuan/workspace/]
I 2024/05/06 01:28:04 conf.go:281: downgraded from version [3.0.12] to [3.0.5]
I 2024/05/06 01:28:04 runtime.go:123: use network proxy [system]
I 2024/05/06 01:28:04 serve.go:115: kernel [pid=1] http server [0.0.0.0:6806] is booting
I 2024/05/06 01:28:04 blocktree.go:495: read block tree [686 B] to [/siyuan/workspace/temp/blocktree], elapsed [0.22s]
I 2024/05/06 01:28:04 conf.go:827: database size [119 kB], tree/block count [1/3]
I 2024/05/06 01:28:04 working.go:192: kernel booted
I 2024/05/06 01:28:04 box.go:76: auto stat [trees=1, blocks=3, dataSize=5.9 MB, assetsSize=5.9 MB]
I 2024/05/06 01:28:15 session.go:116: auth success [ip=182.118.236.55]
I 2024/05/06 01:28:15 serve.go:207: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36]
I 2024/05/06 01:39:01 session.go:116: auth success [ip=182.118.236.55]
I 2024/05/06 01:39:01 serve.go:207: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36]
I 2024/05/06 01:39:09 session.go:116: auth success [ip=182.118.236.55]
I 2024/05/06 01:39:10 serve.go:207: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36]
I 2024/05/06 01:39:23 session.go:116: auth success [ip=182.118.236.55]
I 2024/05/06 01:39:23 serve.go:207: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36]
E 2024/05/06 01:41:26 serve.go:418: handle command failed: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
I 2024/05/06 01:54:13 process.go:36: received os signal [terminated], exit kernel process now
I 2024/05/06 01:54:13 conf.go:565: exiting kernel [force=false, setCurrentWorkspace=true, execInstallPkg=1]
I 2024/05/06 01:54:13 database.go:1249: closed database
I 2024/05/06 01:54:13 conf.go:990: cleared workspace temp
I 2024/05/06 01:54:13 sync.go:712: sync websocket closed
I 2024/05/06 01:56:42 working.go:146: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2024/05/06 01:56:42 runtime.go:74: kernel is booting:
    * ver [3.0.12]
    * arch [amd64]
    * os [alpine]
    * pid [1]
    * runtime mode [prod]
    * working directory [/opt/siyuan]
    * read only [false]
    * container [docker]
    * database [ver=20220501]
    * workspace directory [/siyuan/workspace/]
I 2024/05/06 01:56:42 conf.go:124: loaded conf [/siyuan/workspace/conf/conf.json]
I 2024/05/06 01:56:42 conf.go:283: upgraded from version [3.0.5] to [3.0.12]
I 2024/05/06 01:56:42 runtime.go:123: use network proxy [system]
I 2024/05/06 01:56:42 serve.go:116: kernel [pid=1] http server [0.0.0.0:6806] is booting
I 2024/05/06 01:56:42 blocktree.go:509: read block tree [686 B] to [/siyuan/workspace/temp/blocktree], elapsed [0.00s]
I 2024/05/06 01:56:42 conf.go:848: database size [118.79 kB], tree/block count [1/3]
I 2024/05/06 01:56:42 working.go:192: kernel booted
I 2024/05/06 01:56:42 box.go:76: auto stat [trees=1, blocks=3, dataSize=5.93 MB, assetsSize=5.87 MB]
/siyuan/workspace/temp $
```

**Comment by 88250** [comment] 2024-05-06 01:59
Duplicate of https://github.com/siyuan-note/siyuan/pull/11195

**Closed by 88250** 2024-05-06 01:59 UTC
