### ISSUE TITLE
Can't move notebooks in panel tree

### ISSUE THREAD

**Issue by taozina0587** [siyuan-note/siyuan#6507] opened 2022-11-07 10:25 UTC
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

When creating notebooks in the document tree in the side panel there is no possibility of moving.

### 期待的结果 Expected result

Manual manipulation of notebooks is possible in the side panel.

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/90691302/200287249-195d2b04-fe6b-4129-aaf2-18d1b1d606fb.png)

### 版本环境 Version environment

```markdown
- Version: 2.4.10
- Operating System: Linux
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9950500/siyuan.log)

**Comment by 88250** [comment] 2022-11-07 12:07
Duplicate of https://github.com/siyuan-note/siyuan/issues/6499

**Closed by 88250** 2022-11-07 12:07 UTC
