### ISSUE TITLE
wavedorm 的支持

### ISSUE THREAD

**Issue by heartacker** [siyuan-note/siyuan#7621] opened 2023-03-10 11:42 UTC
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

https://blog.csdn.net/OnlyLove_/article/details/111770771

### 描述可能的最优解决方案 Describe the optimal solution

https://wavedrom.com/tutorial.html#:~:text=Edit%20Me%20%3E%3E-,Step%207,-.The%20config%7B%7D%20property

**Comment by 88250** [comment] 2023-03-11 13:08
Duplicate of https://github.com/siyuan-note/siyuan/issues/2954

目前还是暂时不考虑加入，感谢提议。

**Closed by 88250** 2023-03-11 13:08 UTC
