### ISSUE TITLE
Chatgpt上直接点复制按钮复制过来的文本代码段换行缺失

### ISSUE THREAD

**Issue by ruin1990** [siyuan-note/siyuan#13445] opened 2024-12-12 03:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Chatgpt上直接点复制按钮复制过来的文本代码段换行缺失，但是我直接贴到记事本，然后再贴到思源里是正常的。
![image](https://github.com/user-attachments/assets/299f6bd3-60df-40e5-8dc9-b3f9fea85944)

### Expected result

![image](https://github.com/user-attachments/assets/99bc6c62-3e8d-4ebb-986e-431b006edd7d)

### Screenshot or screen recording presentation

![image](https://github.com/user-attachments/assets/c18a69fd-1459-44c8-bd36-33abbff0e212)

### Version environment

```markdown
- Version: 3.1.15
- Operating System: Win 10
- Browser (if used):
```

### Log file

试了下百度文心一言不会这样
前几天还不会，不太确定是siyuan还是openai有改动

### More information

附上我问的问题：bat脚本我想创建一个文件夹，用当前时间戳命名，格式是title_yyyyMMdd_hhmmss

**Comment by 88250** [comment] 2024-12-12 03:13
Duplicate of https://github.com/siyuan-note/siyuan/issues/13416

**Closed by 88250** 2024-12-12 03:13 UTC

**Comment by ruin1990** [comment] 2024-12-12 10:09
原来是同一个issue，没注意到

**Comment by 88250** [comment] 2024-12-12 10:18
最新的 dev 版已经打包，方便的话请帮忙测试。

**Comment by ruin1990** [comment] 2024-12-17 02:41
测试v3.1.16-dev2问题已解决
