### ISSUE TITLE
Docker 更新到 2.2.2 会导致 ui 问题 | Docker update to 2.2.2 causes ui issues

### ISSUE THREAD

**Issue by N4v41** [siyuan-note/siyuan#5992] opened 2022-09-27 16:18 UTC
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

所有伟大应用的拳头！ 真的很喜欢siyuam作为知识管理器！ 很好！
有时语言是做出更多贡献的障碍，但谷歌翻译无能为力。

问题：
在新的 2.2.2 版本中使用现有数据会使 ui 为空白。

----
Fist of all great aplication !! really loving siyuam as knowledge manger! great job!
some times the language is a barrier to contributing more, but nothing that google translate can't help with.

Problem:
using existing data in the new 2.2.2 version makes the ui to be blank.

### 期待的结果 Expected result

normal ui showing as previous versions

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/45365461/192574446-adfd5d84-d84b-4910-881b-50abb4223419.png)
![image](https://user-images.githubusercontent.com/45365461/192578137-8a9eb45d-6957-464f-9037-6fc78d6c51d7.png)

### 版本环境 Version environment

```markdown
- Version: 2.2.2
- Operating System: linux/docker
- Browser (if used): tested in Firefox and Microsoft Edge
```

### 日志文件 Log file

[si.log](https://github.com/siyuan-note/siyuan/files/9657883/si.log)

### 更多信息 More information

回滚到2.2.1版本，ui正常。
---
roling back to version 2.2.1 and the ui is normal.

**Comment by 88250** [comment] 2022-09-27 16:28
Duplicate of https://github.com/siyuan-note/siyuan/issues/5986

**Closed by 88250** 2022-09-27 16:28 UTC
