### ISSUE TITLE
Bug: Persistent Table Column Sizing in Database Views Not Working

### ISSUE THREAD

**Issue by MrIntellectX** [siyuan-note/siyuan#10942] opened 2024-04-08 19:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

The state of database views is not saving correctly. If I change the column size of a table, close the document, and then reopen it, the changes revert back to the original view. Additionally, when I create another view, it should maintain the same table column sizing as the first view.

### Expected result

Once a user modifies and adjusts the table sizing, it should save that state so that in the future, if the user opens the document, the sizing of the table's columns must be the same as last. Additionally, when the user creates another mirror view of that database, it should use the exact table column size.

### Screenshot or screen recording presentation

https://github.com/siyuan-note/siyuan/assets/36538038/54063617-b500-49ac-bdd2-d4444dff451d

### Version environment

```markdown
- Version: v3.0.7
- Operating System: Win 11 Pro
- Browser (if used): -
```

### Log file

-

**Comment by TCOTC** [comment] 2024-04-08 19:28
Duplicate of #10865

**Closed** 2024-04-09 00:18 UTC
