### ISSUE TITLE
Please enter the title of the bug report

### ISSUE THREAD

**Issue by Tinaliasd** [siyuan-note/siyuan#7815] opened 2023-03-29 05:00 UTC
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

思源内核因未知原因退出 [code=2]，请尝试重启操作系统后再启动思源。如果该问题依然发生，请检查杀毒软件是否阻止思源内核启动。
SiYuan Kernel exited for unknown reasons [code=2], please try to reboot your operating system and then start SiYuan again. If occurs this problem still, please check your anti-virus software whether kill the SiYuan Kernel.

[🔖 v2.8.1](https://b3log.org/siyuan/download.html)

旧版本没有出现问题 2023.03.28升级新版本出现问题

### 期待的结果 Expected result

无

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/87812432/228431031-c52fb8dd-cf6e-4dcd-aade-a932737ccebd.png)

### 版本环境 Version environment

```markdown
- Version: 2.9.1
- Operating System: windows 10
- Browser (if used):
```

### 日志文件 Log file

备注log 中没有显示这个错误,同时log的错误是由于新的功能异常导致的,我的错误发生在2023/03/29 12:55左右,日志中没有这个时间段的

E 2023/03/29 12:46:54 openai.go:53: create chat completion failed: Post "https://api.openai.com/v1/chat/completions": read tcp 127.0.0.1:13995->127.0.0.1:7890: wsarecv: An existing connection was forcibly closed by the remote host.
E 2023/03/29 12:47:46 openai.go:53: create chat completion failed: Post "https://api.openai.com/v1/chat/completions": context deadline exceeded
W 2023/03/29 12:48:01 box.go:110: found a corrupted box [D:\Obsidian\siyuan\SiYuan\data\20230122211550-0dzej0i]
W 2023/03/29 12:48:01 box.go:110: found a corrupted box [D:\Obsidian\siyuan\SiYuan\data\20230122212229-o6thl7l]
W 2023/03/29 12:48:05 box.go:110: found a corrupted box [D:\Obsidian\siyuan\SiYuan\data\20230122211550-0dzej0i]
W 2023/03/29 12:48:05 box.go:110: found a corrupted box [D:\Obsidian\siyuan\SiYuan\data\20230122212229-o6thl7l]
E 2023/03/29 12:48:45 openai.go:53: create chat completion failed: Post "https://api.openai.com/v1/chat/completions": context deadline exceeded
W 2023/03/29 12:48:47 box.go:110: found a corrupted box [D:\Obsidian\siyuan\SiYuan\data\20230122211550-0dzej0i]
W 2023/03/29 12:48:47 box.go:110: found a corrupted box [D:\Obsidian\siyuan\SiYuan\data\20230122212229-o6thl7l]
W 2023/03/29 12:48:48 box.go:110: found a corrupted box [D:\Obsidian\siyuan\SiYuan\data\20230122211550-0dzej0i]
W 2023/03/29 12:48:48 box.go:110: found a corrupted box [D:\Obsidian\siyuan\SiYuan\data\20230122212229-o6thl7l]
E 2023/03/29 12:48:53 openai.go:53: create chat completion failed: Post "https://api.openai.com/v1/chat/completions": read tcp 127.0.0.1:14929->127.0.0.1:7890: wsarecv: An existing connection was forcibly closed by the remote host.
W 2023/03/29 12:49:05 box.go:110: found a corrupted box [D:\Obsidian\siyuan\SiYuan\data\20230122211550-0dzej0i]
W 2023/03/29 12:49:05 box.go:110: found a corrupted box [D:\Obsidian\siyuan\SiYuan\data\20230122212229-o6thl7l]
W 2023/03/29 12:49:06 box.go:110: found a corrupted box [D:\Obsidian\siyuan\SiYuan\data\20230122211550-0dzej0i]
W 2023/03/29 12:49:06 box.go:110: found a corrupted box [D:\Obsidian\siyuan\SiYuan\data\20230122212229-o6thl7l]

**Comment by 88250** [comment] 2023-03-29 05:02
Duplicate of https://github.com/siyuan-note/siyuan/issues/7806

**Closed by 88250** 2023-03-29 05:02 UTC
