### ISSUE TITLE
Markdown export error

### ISSUE THREAD

**Issue by RainBoat** [siyuan-note/siyuan#8609] opened 2023-06-24 16:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

There is no markdown (.md) file in the exported zip, using the defalut export function of the page, while it works well using other format to export

### Expected result

The output should include .md files

### Version environment

```markdown
- Version: 2.9.2
- Operating System: macOS 13.3 (22E252)
- Browser (if used):~
```

### Log file

[siyuan.log.bak.log](https://github.com/siyuan-note/siyuan/files/11857530/siyuan.log.bak.log)

**Comment by 88250** [comment] 2023-06-25 01:03
Duplicate of https://github.com/siyuan-note/siyuan/issues/8587

**Closed by 88250** 2023-06-25 01:03 UTC
