### ISSUE TITLE
请求 增强搜索功能-使用AI语义搜索

### ISSUE THREAD

**Issue by tod-zhang** [siyuan-note/siyuan#11714] opened 2024-06-13 03:49 UTC
### In what scenarios do you need this feature?

当提供open ai api后，在搜索方面增加使用AI语义搜索

### Describe the optimal solution

notion

**Comment by 88250** [comment] 2024-06-13 14:50
Duplicate of https://github.com/siyuan-note/siyuan/issues/8308

**Closed by 88250** 2024-06-13 14:50 UTC
