### ISSUE TITLE
v3.1.16版本，导出的Markdown格式文件内容为空

### ISSUE THREAD

**Issue by worldPuzzle01** [siyuan-note/siyuan#13591] opened 2024-12-23 05:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

思源客户端内容：
![Uploading 1.png…]()
导出后内容：
![Uploading 2.png…]()
![Uploading 3.png…]()

### Expected result

正确导出

### Version environment

```markdown
- Version: v3.1.16
- Operating System: 
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/18225630/siyuan.log)

**Comment by 88250** [comment] 2024-12-23 07:28
Duplicate of https://github.com/siyuan-note/siyuan/issues/13545

**Closed by 88250** 2024-12-23 07:28 UTC
