### ISSUE TITLE
Error quoting

### ISSUE THREAD

**Issue by taozina** [siyuan-note/siyuan#5651] opened 2022-08-16 09:59 UTC
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

When typing "[[" to quote another existing page in Siyuan, the corresponding page box appears in the wrong language.

![image](https://user-images.githubusercontent.com/90691302/184851978-f3785972-8996-469c-a097-f87473819424.png)

### 期待的结果 Expected result

Disappear the "mark" language and become normal.

### 版本环境 Version environment

```markdown
- Version: 2.1.7
- Operating System: Windows 10
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9349658/siyuan.log)

**Comment by 88250** [comment] 2022-08-17 02:14
Duplicate of #5650

**Closed by 88250** 2022-08-17 02:14 UTC

**Comment by bemofan** [comment] 2022-08-19 15:22
![截屏2022-08-19 下午11 21 13](https://user-images.githubusercontent.com/67182689/185652353-be1d6a14-bef9-4a95-b95e-f82acde07024.png)
确实存在这个问题
