### ISSUE TITLE
image blocks now have additional empty space above and below the images

### ISSUE THREAD

**Issue by RobertBJTU** [siyuan-note/siyuan#12157] opened 2024-07-31 10:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

The issue started to appear around version 3.1.1

### Expected result

During the version upgrade, ensure the consistency of the rendering effect of the image blocks.

### Version environment

```markdown
- Version: 3.1.1
- Operating System: Win 10
- Browser (if used):
```

### Log file

None

**Comment by TCOTC** [comment] 2024-07-31 11:35
Duplicate of #12156

**Closed** 2024-07-31 12:36 UTC
