### ISSUE TITLE
Property to change FSRS properties (retention, maximum interval, weights) from doc attributes

### ISSUE THREAD

**Issue by FancyBEAST** [siyuan-note/siyuan#12578] opened 2024-09-24 09:10 UTC
### In what scenarios do you need this feature?

Harder subjects like a new language or easy subjects where we already know a lot should have different set of settings for FSRS. So it will be great if we can edit those properties directly from doc attributes

### Describe the optimal solution

Ideally the FSRS settings should have precedence for the child doc instead of parent doc. (If parent doc has 0.9 as retention rate and child doc has 0.8 and I am studying from the parent doc then FSRS settings for the flashcards in child doc should have 0.8 as retention rate). Anki has the option to set different retention rate, weights etc for each deck using presets.

### Describe the candidate solution

Custom properties to edit all FSRS settings from doc attributes

**Comment by 88250** [comment] 2024-09-24 14:36
Duplicate of https://github.com/siyuan-note/siyuan/issues/10491

**Closed by 88250** 2024-09-24 14:36 UTC
