### ISSUE TITLE
Expand Doc Tree on startup automatically

### ISSUE THREAD

**Issue by anarion80** [siyuan-note/siyuan#12336] opened 2024-08-26 08:16 UTC
### In what scenarios do you need this feature?

Every time I'm starting SiYuan the Doc Tree is collapsed by default. I then need to click several times to get to the view I then use all the time.

Please make the Doc Tree automatically expandable on startup, or have a config option for that, or remember the last state (expanded/collapsed) and start with that.

### Describe the optimal solution

Have the Doc Tree automatically expandable on startup, or have a config option for that, or remember the last state (expanded/collapsed) and start with that.

**Comment by 88250** [comment] 2024-08-26 10:53
Duplicate of https://github.com/siyuan-note/siyuan/issues/10652

**Closed by 88250** 2024-08-26 10:53 UTC
