### ISSUE TITLE
关于内容收纳之后，剪切，丢失内容的bug

### ISSUE THREAD

**Issue by Josephyss** [siyuan-note/siyuan#12208] opened 2024-08-07 03:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![SiYuan_EcAMDupZTV](https://github.com/user-attachments/assets/376ee563-e54a-4d43-be0c-1a62e6574a7b)

### Expected result

再将内容收纳之后使用剪切，结果只会剪切它标题，内容不会在一起剪切

### Version environment

```markdown
pc 3.1.2 
历史版本也有这个问题
```

### Log file

[system-log_2.zip](https://github.com/user-attachments/files/16517724/system-log_2.zip)

**Comment by TCOTC** [comment] 2024-08-07 03:45
Duplicate of ##11865

**Closed** 2024-08-07 12:36 UTC
