### ISSUE TITLE
Floating Panels Not Triggering with 'Hide Dock' Enabled in Immersive Mode

### ISSUE THREAD

**Issue by UsmanTechJive** [siyuan-note/siyuan#12927] opened 2024-10-26 22:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Hello, in this example, I’m using the default SiYuan theme without any CSS modifications, to demonstrate an issue with the "Hide Dock" option at the bottom left.

When I enable "Hide Dock" and use floating panels for both the left menu and right side, I can't access the panels in immersive mode. Normally, moving the mouse to the edges should trigger the panels to appear, but this doesn’t happen here. As a result, I’m unable to show or access the left and right panels.

![image](https://github.com/user-attachments/assets/644b6cd6-db21-43ed-8cd4-9179380022fb)

But when I show the docks, I can easily use the left or right floating panel, as it easily detects the edge.

![image](https://github.com/user-attachments/assets/9167cea0-18a3-4f1b-90e6-0ec703458acd)

### Expected result

When the left or right panels are in floating mode and the "Hide Dock" option is enabled, implement edge detection near the left and right sides of the screen to trigger the panels. 

- Add a small invisible "trigger zone" along the left and right edges of the screen.
- When the user hovers near the left or right edge (within the trigger zone), it should automatically detect the mouse movement and reveal the corresponding panel (left or right).

This way, users can easily access the floating panels even in immersive mode with the "Hide Dock" option enabled.

Alternatively, I’ve managed to make it work with CSS by adding a margin around it, as shown in the image below, but it’s still not smooth. I have to move the mouse very carefully to the edge for it to detect and show the floating panel.

![image](https://github.com/user-attachments/assets/deed4850-1039-412c-9f21-e5bdcd40b4f8)

![image](https://github.com/user-attachments/assets/9b453d2b-dd22-4b52-832d-dddb87de9fdb)

If you have a better approach or logic in mind, I’d appreciate it!

### Version environment

```markdown
- Version: 3.1.10
- Operating System: Windows 11 Pro
- Browser (if used):
```

### Log file

-

**Comment by 88250** [comment] 2024-10-27 03:23
Duplicate of https://github.com/siyuan-note/siyuan/issues/9136

**Closed by 88250** 2024-10-27 03:23 UTC
