### ISSUE TITLE
反链支持设置默认排序

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11863] opened 2024-06-30 09:36 UTC
### In what scenarios do you need this feature?

https://ld246.com/article/1719739245875 第二点

### Describe the optimal solution

。

**Comment by 88250** [comment] 2024-06-30 15:42
Duplicate of https://github.com/siyuan-note/siyuan/issues/7764

**Closed by 88250** 2024-06-30 15:42 UTC
