### ISSUE TITLE
功能请求：标签支持搜索

### ISSUE THREAD

**Issue by SaXz2** [siyuan-note/siyuan#12632] opened 2024-09-27 19:01 UTC
### In what scenarios do you need this feature?

目前的标签面板的标签越来多以后不容易查找希望添加一个筛选的功能

### Describe the optimal solution

![image](https://github.com/user-attachments/assets/4f54f569-9c58-4399-b8ce-dc59fa997f83)

**Comment by TCOTC** [comment] 2024-09-28 01:01
Duplicate of #11039

**Closed** 2024-09-28 03:10 UTC
