### ISSUE TITLE
通过修改大纲顺序来重排文章内容

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#9784] opened 2023-11-29 13:51 UTC
### In what scenarios do you need this feature?

调整文章的顺序

### Describe the optimal solution

通过修改大纲顺序来重排文章内容

**Comment by 88250** [comment] 2023-11-29 13:58
Duplicate of https://github.com/siyuan-note/siyuan/issues/7957

**Closed by 88250** 2023-11-29 13:58 UTC
