### ISSUE TITLE
集市添加全部更新按钮

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#10656] opened 2024-03-19 14:30 UTC
### In what scenarios do you need this feature?

一键更新所有插件、主题等

### Describe the optimal solution

添加全部更新按钮

**Comment by 88250** [comment] 2024-03-19 14:38
Duplicate of https://github.com/siyuan-note/siyuan/issues/8390

**Closed by 88250** 2024-03-19 14:38 UTC
