### ISSUE TITLE
嵌入块支持与定义块交换

### ISSUE THREAD

**Issue by AvoidantPerDis** [siyuan-note/siyuan#12722] opened 2024-10-07 08:47 UTC
### In what scenarios do you need this feature?

2个文档同时编辑相同内容

### Describe the optimal solution

类似引用块

### Describe the candidate solution

只对单id生效

**Comment by TCOTC** [comment] 2024-10-07 09:10
Duplicate of #11976

**Closed** 2024-10-07 10:46 UTC
