### ISSUE TITLE
docker部署，浏览器访问报错GET http://mydomain.com/stage/protyle/js/pdf/pdf.js?v=1.6.3 net::ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by andy65007** [siyuan-note/siyuan#5658] opened 2022-08-17 02:43 UTC
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

直接使用官方docker镜像说明中的docker命令启动思源服务，成功。客户端浏览器(chrome最新)访问时，console报错：
main.0e473a8f1a05dd34d107.js:1          GET http://mydomain.com/stage/protyle/js/pdf/pdf.js?v=1.6.3 net::ERR_CONNECTION_TIMED_OUT
t.addScriptSync @ main.0e473a8f1a05dd34d107.js:1
...
我访问的URL包含端口，而日志中域名mydomain.com后没有端口，会不会源码某个地方少了端口导致？

### 期待的结果 Expected result

修正错误

### 版本环境 Version environment

```markdown
- Version: 最新2022.8
- Operating System: CentOS 8 64
- Browser (if used):chrome最新
```

### 日志文件 Log file

main.0e473a8f1a05dd34d107.js:1          GET http://note.liuxiaoyi.com/stage/protyle/js/pdf/pdf.js?v=1.6.3 net::ERR_CONNECTION_TIMED_OUT
t.addScriptSync @ main.0e473a8f1a05dd34d107.js:1
9492 @ main.0e473a8f1a05dd34d107.js:1
n @ main.0e473a8f1a05dd34d107.js:1
8884 @ main.0e473a8f1a05dd34d107.js:1
n @ main.0e473a8f1a05dd34d107.js:1
4862 @ main.0e473a8f1a05dd34d107.js:1
n @ main.0e473a8f1a05dd34d107.js:1
5151 @ main.0e473a8f1a05dd34d107.js:1
n @ main.0e473a8f1a05dd34d107.js:1
7683 @ main.0e473a8f1a05dd34d107.js:1
n @ main.0e473a8f1a05dd34d107.js:1
8888 @ main.0e473a8f1a05dd34d107.js:1
n @ main.0e473a8f1a05dd34d107.js:1
4868 @ main.0e473a8f1a05dd34d107.js:1
n @ main.0e473a8f1a05dd34d107.js:1
8890 @ main.0e473a8f1a05dd34d107.js:1
n @ main.0e473a8f1a05dd34d107.js:1
5841 @ main.0e473a8f1a05dd34d107.js:1
n @ main.0e473a8f1a05dd34d107.js:1
4256 @ main.0e473a8f1a05dd34d107.js:1
n @ main.0e473a8f1a05dd34d107.js:1
7396 @ main.0e473a8f1a05dd34d107.js:1
n @ main.0e473a8f1a05dd34d107.js:1
7813 @ main.0e473a8f1a05dd34d107.js:1
n @ main.0e473a8f1a05dd34d107.js:1
5933 @ main.0e473a8f1a05dd34d107.js:1
n @ main.0e473a8f1a05dd34d107.js:1
1787 @ main.0e473a8f1a05dd34d107.js:1
n @ main.0e473a8f1a05dd34d107.js:1
4853 @ main.0e473a8f1a05dd34d107.js:1
n @ main.0e473a8f1a05dd34d107.js:1
4976 @ main.0e473a8f1a05dd34d107.js:1
n @ main.0e473a8f1a05dd34d107.js:1
5322 @ main.0e473a8f1a05dd34d107.js:1
n @ main.0e473a8f1a05dd34d107.js:1
16 @ main.0e473a8f1a05dd34d107.js:1
n @ main.0e473a8f1a05dd34d107.js:1
3725 @ main.0e473a8f1a05dd34d107.js:1
n @ main.0e473a8f1a05dd34d107.js:1
5148 @ main.0e473a8f1a05dd34d107.js:1
n @ main.0e473a8f1a05dd34d107.js:1
4529 @ main.0e473a8f1a05dd34d107.js:1
n @ main.0e473a8f1a05dd34d107.js:1
2936 @ main.0e473a8f1a05dd34d107.js:1
n @ main.0e473a8f1a05dd34d107.js:1
8887 @ main.0e473a8f1a05dd34d107.js:1
n @ main.0e473a8f1a05dd34d107.js:1
618 @ main.0e473a8f1a05dd34d107.js:1
n @ main.0e473a8f1a05dd34d107.js:1
4489 @ main.0e473a8f1a05dd34d107.js:1
n @ main.0e473a8f1a05dd34d107.js:1
6154 @ main.0e473a8f1a05dd34d107.js:1
n @ main.0e473a8f1a05dd34d107.js:1
8842 @ main.0e473a8f1a05dd34d107.js:1
n @ main.0e473a8f1a05dd34d107.js:1
5960 @ main.0e473a8f1a05dd34d107.js:1
n @ main.0e473a8f1a05dd34d107.js:1
(anonymous) @ main.0e473a8f1a05dd34d107.js:1
(anonymous) @ main.0e473a8f1a05dd34d107.js:1
(anonymous) @ main.0e473a8f1a05dd34d107.js:1
Show 30 more frames
main.0e473a8f1a05dd34d107.js:1 Uncaught DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://note.liuxiaoyi.com/stage/protyle/js/pdf/pdf.js?v=1.6.3'.
    at t.addScriptSync (http://note.liuxiaoyi.com:13002/stage/build/desktop/main.0e473a8f1a05dd34d107.js:1:956649)
    at 9492 (http://note.liuxiaoyi.com:13002/stage/build/desktop/main.0e473a8f1a05dd34d107.js:1:322017)
    at n (http://note.liuxiaoyi.com:13002/stage/build/desktop/main.0e473a8f1a05dd34d107.js:1:1194173)
    at 8884 (http://note.liuxiaoyi.com:13002/stage/build/desktop/main.0e473a8f1a05dd34d107.js:1:34240)
    at n (http://note.liuxiaoyi.com:13002/stage/build/desktop/main.0e473a8f1a05dd34d107.js:1:1194173)
    at 4862 (http://note.liuxiaoyi.com:13002/stage/build/desktop/main.0e473a8f1a05dd34d107.js:1:322254)
    at n (http://note.liuxiaoyi.com:13002/stage/build/desktop/main.0e473a8f1a05dd34d107.js:1:1194173)
    at 5151 (http://note.liuxiaoyi.com:13002/stage/build/desktop/main.0e473a8f1a05dd34d107.js:1:358743)
    at n (http://note.liuxiaoyi.com:13002/stage/build/desktop/main.0e473a8f1a05dd34d107.js:1:1194173)
    at 7683 (http://note.liuxiaoyi.com:13002/stage/build/desktop/main.0e473a8f1a05dd34d107.js:1:564317)

**Comment by 88250** [comment] 2022-08-17 02:49
Duplicate of #5656

**Closed by 88250** 2022-08-17 02:49 UTC
