### ISSUE TITLE
为集市提供搜索功能

### ISSUE THREAD

**Issue by mdzz2048** [siyuan-note/siyuan#9039] opened 2023-08-24 11:38 UTC
### In what scenarios do you need this feature?

目前集市的插件已经超过六十个，平时常用的也有十几个，希望可以出一个搜索功能，方便查找插件。

目前只能通过“已下载-插件”管理插件，每次都要从这么多插件里找到想要的很费劲。

At present, the market has more than 60 plug-ins, usually there are more than 10 commonly used, I hope that a search function to facilitate the search for plug-ins. 

Currently the only way to manage plugins is through the“Downloaded-plugins” section, and it's hard to find what you're looking for with so many plugins at a time.

![image](https://github.com/siyuan-note/siyuan/assets/86549958/b0b47fec-1175-4491-a64f-f0b65f6c2d68)

### Describe the optimal solution

为集市“已下载”界面和“插件界面”提供搜索框。

Provides a search box for the“Downloaded” and“Plug-in” interfaces of the marketplace.

### Describe the candidate solution

为集市所有页签提供搜索框

Provides a search box for all marquee tabs

**Comment by 88250** [comment] 2023-08-24 15:32
Duplicate of https://github.com/siyuan-note/siyuan/issues/8173

**Closed by 88250** 2023-08-24 15:32 UTC
