### ISSUE TITLE
Kernel exited for unknown reasons

### ISSUE THREAD

**Issue by SensibleHeuristics** [siyuan-note/siyuan#7822] opened 2023-03-29 08:49 UTC
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

Si Yuan desktop on Windows 11 exited frequently with the message : kernel exited for unknown reasons"
![SiYuanError](https://user-images.githubusercontent.com/129269596/228476640-79116a0e-7ccb-4833-a140-a13c098919ff.png)

### 期待的结果 Expected result

no more kernel exits

### 截屏或者录屏演示 Screenshot or screen recording presentation

![SiYuanError](https://user-images.githubusercontent.com/129269596/228476886-7cc17bee-b8ab-46d8-b3c6-0e9f5acf5a52.png)

### 版本环境 Version environment

```markdown
- Version: 2.8.1.0
- Operating System: Windows 11
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/11098433/siyuan.log)

**Comment by fwzuw** [comment] 2023-03-29 08:57
Duplicate of https://github.com/siyuan-note/siyuan/issues/7806
https://github.com/siyuan-note/siyuan/releases/tag/v2.8.2-dev1

**Closed** 2023-03-29 09:42 UTC
