### ISSUE TITLE
数据库删除后，对应的json会残留

### ISSUE THREAD

**Issue by holduan** [siyuan-note/siyuan#12647] opened 2024-09-29 07:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如题，被删除的数据库中引用的资源也会残留（不会出现在 `未被引用的资源` 中）

https://github.com/user-attachments/assets/5f3a85a4-8ede-4053-8a95-e40ee3e3e0ab

### Expected result

.

### Version environment

```markdown
- Version: 3.1.7
- Operating System: 
- Browser (if used):
```

### Log file

.

**Comment by TCOTC** [comment] 2024-09-29 07:43
Duplicate of #11569

**Comment by holduan** [comment] 2024-09-29 08:24
> Duplicate of #11569

ok，谢谢。原来这个那么早就提了啊

**Closed** 2024-09-29 08:27 UTC
