### ISSUE TITLE
启动思源后点击文章的大纲标题，会切换成导出浏览模式

### ISSUE THREAD

**Issue by 5kyfkr** [siyuan-note/siyuan#12500] opened 2024-09-16 16:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![动画](https://github.com/user-attachments/assets/752c0892-c434-4dc9-a161-e45afcfe967a)
如图，第一次打开工作空间或者重新启动思源后，点击随意一个文章的大纲目录，就会切换成导出浏览模式。

### Expected result

不自动切换成浏览模式

### Version environment

```markdown
- Version: 3.0.17 dev4
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by TCOTC** [comment] 2024-09-17 02:11
Duplicate of https://github.com/siyuan-note/siyuan/issues/11981#issuecomment-2353391539

**Comment by 88250** [comment] 2024-09-17 15:02
在 https://github.com/siyuan-note/siyuan/issues/11981 中继续处理 @Vanessa219

**Closed by 88250** 2024-09-17 15:02 UTC
Labels: Bug
