### ISSUE TITLE
In the two default theme modes, icons do not load correctly.

### ISSUE THREAD

**Issue by taozina0587** [siyuan-note/siyuan#6979] opened 2023-01-03 09:11 UTC
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

![image](https://user-images.githubusercontent.com/90691302/210327695-55df2ad0-397a-4ebf-ba26-7e9c4adbd12b.png)

![image](https://user-images.githubusercontent.com/90691302/210327741-5d2bf019-c45b-4bf6-9e02-6d369372f1ba.png)

### 期待的结果 Expected result

full loading of resources.

### 版本环境 Version environment

```markdown
- Version: 2.6.1
- Operating System: Linux
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/10335344/siyuan.log)

**Comment by taozina0587** [comment] 2023-01-03 09:17
I went back to version 2.6.0! But soon after, I opened version 2.6.1! It's back to normal! I don't know if it still remains an issue now.

**Comment by zxhd863943427** [comment] 2023-01-03 09:42
As far as I know, this is a problem that occurs when you create a new working directory, and when you use a lower version of siyuan to make up for the missing files, then the problem looks like it goes away. However, there is no doubt that the problem will still occur when you install siyuan on a new computer or create a new workspace

**Comment by 88250** [comment] 2023-01-03 10:11
Duplicate of https://github.com/siyuan-note/siyuan/issues/6974

**Closed by 88250** 2023-01-03 10:11 UTC
