### ISSUE TITLE
使用 Shift+Enter，Delete 键合并后一个块内容时的排版问题

### ISSUE THREAD

**Issue by metoss** [siyuan-note/siyuan#11120] opened 2024-04-23 09:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在一个块的尾部按下 Shift+Enter 键换行，然后使用 Delete 键合并下一个块，会出现排版问题。 默认字体和第三方字体有不同的异常表现：
1. 默认字体： 鼠标选中块时可以看到隐藏的块，被合并内容字体显示异常的白色的背景
2. 第三方字体： 会出现 CSS 代码、鼠标选中 Delete 键后合并的字体时的白色背景。

### Expected result

没有排版的问题。
合并方式最好符合直感，当 delete 后应该直接将下一个块内容移动到鼠标光标后边并完成块合并，现在是先合并到第一行在 Shift + Enter 换行；

### Screenshot or screen recording presentation

默认字体问题：
<img width="1054" alt="image" src="https://github.com/siyuan-note/siyuan/assets/30105272/4e612340-743c-4893-8a3c-8f232a38501b">
第三方字体问题：
![mege_two_blocks](https://github.com/siyuan-note/siyuan/assets/30105272/9cb48014-6cad-43df-aa25-f50ce3d848a9)

### Version environment

```markdown
- Version: 3.0.11
- Operating System: win11
- Browser (if used): no
```

### Log file

no need

**Comment by 88250** [comment] 2024-04-23 09:39
Duplicate of https://github.com/siyuan-note/siyuan/issues/11118

**Closed by 88250** 2024-04-23 09:39 UTC
