### ISSUE TITLE
plugin文件问题

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#13067] opened 2024-11-06 15:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

```
{
  "name": "siyuan-bullet-threading",
  "author": "anarion80",
  "url": "https://github.com/anarion80/siyuan-bullet-threading",
  "version": "0.1.1",
  "minAppVersion": "3.0.12",
  "backends": [
    "windows",
    "linux",
    "darwin",
    "docker",
    "ios",
    "android"
  ],
  "frontends": [
    "desktop",
    "mobile",
    "browser-desktop",
    "browser-mobile",
    "desktop-window"
  ],
  "displayName": {
    "en_US": "Bullet threading for lists",
    "pl_PL": "Linie łączące elementy zagnieżdżonych list"
  },
  "description": {
    "en_US": "A plugin that adds nice lines to nested list elements (bullets). Based on simliar plugin for LogSeq.",
    "pl_PL": "Wtyczka dodająca estetyczne linie łączące elementy zagnieżdżonych list. Bazuje na podobnej wtyczce dla LogSeq."
  },
  "readme": {
    "default": "README.md",
    "en_US": "README.md",
    "pl_PL": "README_pl_PL.md"
  },
  "keywords": [
    "plugin",
    "bullet",
    "threading",
    "nested",
    "list"
  ]
}
```

集市里这个插件，没有 "displayName"、"description"两个字段的默认值，所以集市的已下载列表里不会显示这个插件

集市挂件暂未测试

### Expected result

可否做一下兼容处理，以及集市审查时自动检测

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by TCOTC** [comment] 2024-11-06 16:02
Duplicate of #13053

**Closed** 2024-11-06 16:09 UTC
