### ISSUE TITLE
Database Properties not shown

### ISSUE THREAD

**Issue by n12k0** [siyuan-note/siyuan#11047] opened 2024-04-15 17:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

When adding some pages to a database in SiYuan, the database properties assigned during the creation of these pages do not appear on their property pages. This issue prevents viewing and editing the properties from the individual page view, which is essential for managing data consistency within the database. This only happens with some pages. Sometimes a page has properties and minutes later they are gone

### Expected result

Open SiYuan and navigate to any database.
 Create a new page within this database.
Assign properties to the new page during the creation process.
Once the page is created, open the page and navigate to the 'Property' section.
Expected behavior: The properties assigned during page creation should be visible and editable on the property page.

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/164806400/192fa185-b1e8-44ab-9ecd-da4c8472f212)

![image](https://github.com/siyuan-note/siyuan/assets/164806400/e6507583-670b-433e-979c-6b4e03ac4ce3)

### Version environment

```markdown
- Version: v3.0.9
- Operating System: Windows 11
```

### Log file

main.3aa906b9cb5bacd9881b.js:3848 fetch post error TypeError: Failed to fetch
    at w (main.3aa906b9cb5bacd9881b.js:3848:2731)
    at Sg (main.3aa906b9cb5bacd9881b.js:1424:638)
    at main.3aa906b9cb5bacd9881b.js:1534:837
    at NodeList.forEach (<anonymous>)
    at HTMLDivElement.<anonymous> (main.3aa906b9cb5bacd9881b.js:1534:736)
    at Jn (main.3aa906b9cb5bacd9881b.js:1545:333)
    at Fb (main.3aa906b9cb5bacd9881b.js:3960:2819)
    at main.3aa906b9cb5bacd9881b.js:4060:4840
    at main.3aa906b9cb5bacd9881b.js:3848:3185
[127.0.0.1-1713203016468.log](https://github.com/siyuan-note/siyuan/files/14982612/127.0.0.1-1713203016468.log)

**Comment by 88250** [comment] 2024-04-16 01:25
Hello, I'm not sure about the problem, please see my steps:

[issue.webm](https://github.com/siyuan-note/siyuan/assets/873584/b07b6aa4-d2d0-462d-a760-534f24edcc1f)

**Comment by n12k0** [comment] 2024-04-16 11:27
It seems to happen only on some databases, as you can see.
Afterward I created a new one and could not reproduce the problem...
Maybe you can see what's going on, on the logs I uploaded.
Thank you for your time!
![databaseerror](https://github.com/siyuan-note/siyuan/assets/164806400/1a92154f-f7c9-41b9-b4f8-9b977070c62b)
(sorry for the bad screen recording, but I for privacy reasons I did not want to show the contents of the existing database where the error is happening. If you need a better recording I will send it you privately)

**Comment by 88250** [comment] 2024-04-17 01:27
In the log, I saw that a plug-in `SiYuan-Attribute-Panel` reported an error. Please close the plug-in and test again:

```
main.3aa906b9cb5bacd9881b.js:3848 fetch post error TypeError: Failed to fetch
     at Object.w [as fetchPost] (main.3aa906b9cb5bacd9881b.js:3848:2731)
     at o (plugin:SiYuan-Attribute-Panel:37:2450)
     at eval (plugin:SiYuan-Attribute-Panel:37:2428)
     at main.3aa906b9cb5bacd9881b.js:3848:3185
```

**Comment by n12k0** [comment] 2024-04-17 14:13
hey, here are the logs. This time the `SiYuan-Attribute-Panel` plugin is out. The error persists. 
[127.0.0.1-1713363091329.log](https://github.com/siyuan-note/siyuan/files/15012270/127.0.0.1-1713363091329.log)

**Comment by 88250** [comment] 2024-04-17 14:28
Is the version v3.0.10?

**Comment by n12k0** [comment] 2024-04-17 18:02
I just updated but error persists in v3.0.10. :( 
The database must have been corrupted somehow. I will just build a new one to replace it.  Thank you for your time and patience. 

[127.0.0.1-1713376748907.log](https://github.com/siyuan-note/siyuan/files/15015353/127.0.0.1-1713376748907.log)

**Comment by 88250** [comment] 2024-04-18 01:27
I still can’t find the reason. Is it convenient to export the problematic document as .sy.zip and send it to us for debugging? 845765@qq.com

**Comment by n12k0** [comment] 2024-04-18 11:52
So sorry, I already deleted it and I am not sure how to recover it without loosing the changes. When I go to file history i does not allow me to simply copy the database and if I rollback I loose everything I did since...

**Comment by 88250** [comment] 2024-04-18 12:11
Okay, that's it for the time being. If the problem can be reproduced in the future, please continue to provide feedback. 

I will close the issue first. Thank you.

**Closed by 88250** 2024-04-18 12:11 UTC

**Comment by n12k0** [comment] 2024-04-18 16:32
ok, thank you for your time
