### ISSUE TITLE
Ability to take video notes with timestamps.

### ISSUE THREAD

**Issue by FancyBEAST** [siyuan-note/siyuan#13373] opened 2024-12-04 23:17 UTC
### In what scenarios do you need this feature?

Siyuan already has option to embed videos. If it can support taking notes with timestamps then it can help a lot with note taking from lectures.

### Describe the optimal solution

Ideally I would love SiYuan to have the ability to create timestamps for local videos, Youtube videos (for international users), bilibili or whichever is the Most popular video streaming website for Chinese users. And rest maybe implemented via plugins. Example: [logseq's implementation on youtube timestamps](https://docs.logseq.com/#/page/youtube%20timestamp), [Obsidian Media Extended](https://github.com/PKM-er/media-extended) - Supports youtube, viemo, bilibili, Coursera

### Describe the candidate solution

Same as above

**Comment by 88250** [comment] 2024-12-05 01:35
Duplicate of https://github.com/siyuan-note/siyuan/issues/3504

**Closed by 88250** 2024-12-05 01:35 UTC

**Comment by pakeh2866** [comment] 2024-12-06 00:56
> Thank you for your response! 🙏 I looked into the issue and found some helpful articles. However, they all require a login to access. 😭😭 Since I'm not from mainland China, I would really appreciate it if someone could help me read them.感谢您的回复！ 🙏 我研究了这个问题并发现了一些有用的文章。然而，它们都需要登录才能访问。原因是我不是中国大陆人，如果有人能帮我读一下，我将不胜感激。

https://siyuannote.site/x/20241206085518-ogaj676 come from ld246.com

**Comment by Wetoria** [comment] 2024-12-06 06:52
> Thank you for your response! 🙏 I looked into the issue and found some helpful articles. However, they all require a login to access. 😭😭 Since I'm not from mainland China, I would really appreciate it if someone could help me read them.感谢您的回复！ 🙏 我研究了这个问题并发现了一些有用的文章。然而，它们都需要登录才能访问。原因是我不是中国大陆人，如果有人能帮我读一下，我将不胜感激。

This [link](https://simplest-frontend.feishu.cn/docx/B3NndXHi7oLLXJxnxQmcczRsnse#share-LaiadQHrRoWLMhxKMIec0ElMnTc) doesn't need login to see. Can you visit it?

I don't know about your chinese level, if you have any question  contact me.

**Comment by KuiyueRO** [comment] 2025-01-06 20:11
> Thank you for your response! 🙏 I looked into the issue and found some helpful articles. However, they all require a login to access. 😭😭 Since I'm not from mainland China, I would really appreciate it if someone could help me read them.

https://liuyun.io/article/1736193708090
