### ISSUE TITLE
文字替换为标签的bug

### ISSUE THREAD

**Issue by tagaga** [siyuan-note/siyuan#11090] opened 2024-04-19 13:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

一段文字，想将其中一个字替换为标签，比如“张”字替换为“#张三#”

### Expected result

替换后应该显示为文字为“张三”的标签

### Screenshot or screen recording presentation

<img width="536" alt="be049dae8085c9dea4ad4416778435ed" src="https://github.com/siyuan-note/siyuan/assets/12218511/77228111-b247-4c98-a38e-7314e8d5f7bb">

### Version environment

```markdown
- Version: 3.0.10
- Operating System: win11
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/15041390/siyuan.log)

### More information

已经在QQ群中反馈，重建索引后问题依旧

**Comment by 88250** [comment] 2024-04-19 14:50
Duplicate of https://github.com/siyuan-note/siyuan/issues/11058

**Closed by 88250** 2024-04-19 14:50 UTC
