### ISSUE TITLE
数据库排序单元格选择有问题

### ISSUE THREAD

**Issue by hzxgi** [siyuan-note/siyuan#12937] opened 2024-10-27 08:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

1.创建数据库并设置排序为时间降序
2.创建一行
3.单元格正确创建，但光标并不在改行

### Expected result

3.正确创建单元格并且光标在排序后的该行

### Screenshot or screen recording presentation

![image](https://github.com/user-attachments/assets/9c9fad0e-5963-4040-a45e-3d072f09432a)
![image](https://github.com/user-attachments/assets/e37a87da-a8ac-436a-8ddd-3380767b5aad)
![image](https://github.com/user-attachments/assets/c712d975-a562-484b-9c73-2d170cb42caf)

### Version environment

```markdown
- Version: 3.1.10
- Operating System: Windows11
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/17533295/siyuan.log)

**Comment by 88250** [comment] 2024-10-27 08:55
Duplicate of https://github.com/siyuan-note/siyuan/issues/11100

**Closed by 88250** 2024-10-27 08:55 UTC
