### ISSUE TITLE
一个小问题：锚文本、标题等输入框，无法通过←、→调整输入交点

### ISSUE THREAD

**Issue by zhoutaosheng** [siyuan-note/siyuan#9085] opened 2023-09-01 05:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

无法通过←、→来调整输入焦点
比如下图中，我想按一下←，将输入焦点放到`u`字符之前，做不到
![image](https://github.com/siyuan-note/siyuan/assets/5683995/5eaf2dd3-f756-443c-89df-5fffd13e3433)

- 锚文本、标题、链接等输入框都有这样的问题
- Home、End等键，将输入焦点放到行首和行尾是没有问题的

### Expected result

能正确响应

### Version environment

```markdown
- Version: 2.10.2
- Operating System: Win11
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment] 2023-09-01 08:26
Duplicate of https://github.com/siyuan-note/siyuan/issues/9076

**Closed by 88250** 2023-09-01 08:26 UTC
