### ISSUE TITLE
每次更新后 固定在任务栏的思源笔记图标会自动消失

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#9877] opened 2023-12-14 08:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

每次更新后 固定在任务栏的思源笔记图标会自动消失

### Expected result

不会自动消失

### Version environment

```markdown
- Version: 2.11.2
- Operating System: windows 11
- Browser (if used): edge
```

### Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/13670632/system-log.zip)

**Comment by 88250** [comment] 2023-12-14 09:01
Duplicate of https://github.com/siyuan-note/siyuan/issues/3773

**Closed by 88250** 2023-12-14 09:01 UTC
