### ISSUE TITLE
Heading with emoji and Korean Character input

### ISSUE THREAD

**Issue by jakekwak** [siyuan-note/siyuan#415] opened 2020-11-03 15:12 UTC
Heading without emoji
![siyuan1](https://user-images.githubusercontent.com/15811943/98003525-2ef5f080-1e32-11eb-96c1-8054ac94076e.gif)

Heading with emoji
![siyuan2](https://user-images.githubusercontent.com/15811943/98003582-3a491c00-1e32-11eb-8f18-7f4188e1cf81.gif)

**Comment by 88250** [comment] 2020-11-03 15:56
Sorry, I didn't understand the problem....

**Comment by jakekwak** [comment] 2020-11-03 22:17
@88250 I can not input the second character. 

If you type "ㅐ" after typing "ㅌ", the letter disappears and I cannot type after that. (Only when an emoji is selected using enter)

![siyuan5](https://user-images.githubusercontent.com/15811943/98046320-5c13c480-1e6d-11eb-9807-c4352dcaf7e9.gif)

other cases

no emoji
![siyuan3](https://user-images.githubusercontent.com/15811943/98046425-8cf3f980-1e6d-11eb-9077-8f9046f1746d.gif)
typing full name
![siyuan4](https://user-images.githubusercontent.com/15811943/98046430-91201700-1e6d-11eb-8696-a68c4eb1b274.gif)

**Comment by 88250** [comment] 2020-11-08 11:28
Please open the dev tool and check whether occurs errors in the Console.

**Comment by jakekwak** [comment] 2020-11-10 06:26
@88250 There are no error message.

**Comment by 88250** [comment] 2021-01-06 00:31
I closed it first. If there is any feedback, please continue to follow the post to explain, thank you.

**Closed by 88250** 2021-01-06 00:31 UTC

**Comment by jakekwak** [comment] 2021-02-19 14:57
Is it possible to turn on the debugger option? I want to check the return value of spinvditorirblockdom.

**Comment by Vanessa219** [comment] 2021-02-19 16:21
It's Microsoft Pinyin? 

It may be caused by `compositionend` being triggered when the spelling is not completed.
