### ISSUE TITLE
Export to Markdown and EPUB does not work

### ISSUE THREAD

**Issue by NTEC-dev** [siyuan-note/siyuan#13597] opened 2024-12-24 02:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Exporting to Markdown or EPUB produces a corrupted zip file. The size of this file is 22 byte!
Reproduced on Mac OS 15.2. Please consider a fix as soon as possible. Thansks.

### Expected result

Proper export to markdown or Epub files.

### Version environment

```markdown
- Version: 3.1.16
- Operating System: Mac 15.2
- Browser (if used): Chrome
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/18235126/siyuan.log)

**Comment by Temacc0531** [comment] 2024-12-24 02:28
Duplicate of https://github.com/siyuan-note/siyuan/issues/13545

**Closed** 2024-12-24 02:30 UTC
