### ISSUE TITLE
New notebook sort system

### ISSUE THREAD

**Issue by taozina0587** [siyuan-note/siyuan#7142] opened 2023-01-21 12:50 UTC
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

Currently it is only possible to sort all notebooks in the...

![image](https://user-images.githubusercontent.com/90691302/213867483-a11e5c51-610d-46b3-9fdc-fa6673a22dee.png)

But there are notebooks that I want a different classification than the standard. I would like to suggest an individual sort for each notebook.

When clicking on a notebook, when opening the menu there would be the "sort" option as well.

![image](https://user-images.githubusercontent.com/90691302/213867533-22bf276f-0d19-472d-bbdb-35a4a576b9f0.png)

### 描述可能的最优解决方案 Describe the optimal solution

New system for sort notebook.

**Comment by 88250** [comment] 2023-01-22 03:28
Duplicate of https://github.com/siyuan-note/siyuan/issues/3623

**Closed by 88250** 2023-01-22 03:28 UTC
