### ISSUE TITLE
webui 显示异常

### ISSUE THREAD

**Issue by gitduk** [siyuan-note/siyuan#6001] opened 2022-09-28 04:56 UTC
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

webui 显示异常, 菜单界面透明。

### 期待的结果 Expected result

显示正确

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/48339766/192689620-cdee5e57-10b7-4b10-9b0f-9d92a4ae7104.png)
![image](https://user-images.githubusercontent.com/48339766/192690287-542682ad-96ed-42a4-90e2-a44c4a56a6de.png)

### 版本环境 Version environment

```markdown
- Version: 2.2.2
- Operating System: Ubuntu
- Browser (if used): Google Chrome 105.0.5195.52
```

### 日志文件 Log file

I 2022/09/28 12:36:09 working.go:111: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2022/09/28 12:36:09 runtime.go:47: kernel is booting:
    * ver [2.2.2]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [/opt/siyuan]
    * read only [false]
    * container [docker]
    * database [ver=20220501]
    * workspace directory [/siyuan/workspace/, data 20 kB]
D 2022/09/28 12:36:09 conf.go:121: check device locale failed [detect: not detected], using default language [en_US]
I 2022/09/28 12:36:09 serve.go:79: kernel is booting [http://0.0.0.0:6806]
I 2022/09/28 12:36:09 database.go:73: the database structure is changed, rebuilding database...
I 2022/09/28 12:36:09 database.go:93: reinitialized database [/siyuan/workspace/temp/siyuan.db]
I 2022/09/28 12:36:09 conf.go:559: database size [4.1 kB], tree/block count [0/0]
I 2022/09/28 12:36:09 working.go:151: kernel booted
I 2022/09/28 12:36:25 process.go:46: received os signal [interrupt], exit kernel process now
I 2022/09/28 12:36:25 conf.go:363: exiting kernel [force=false, execInstallPkg=1]
I 2022/09/28 12:36:25 database.go:1122: closed database
I 2022/09/28 12:36:25 conf.go:616: cleared workspace temp
I 2022/09/28 12:36:31 working.go:111: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2022/09/28 12:36:31 runtime.go:47: kernel is booting:
    * ver [2.2.2]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [/opt/siyuan]
    * read only [false]
    * container [docker]
    * database [ver=20220501]
    * workspace directory [/siyuan/workspace/, data 20 kB]
I 2022/09/28 12:36:31 serve.go:79: kernel is booting [http://0.0.0.0:6806]
I 2022/09/28 12:36:31 conf.go:559: database size [74 kB], tree/block count [0/0]
I 2022/09/28 12:36:31 working.go:151: kernel booted
I 2022/09/28 12:36:38 process.go:46: received os signal [interrupt], exit kernel process now
I 2022/09/28 12:36:38 conf.go:363: exiting kernel [force=false, execInstallPkg=1]
I 2022/09/28 12:36:38 database.go:1122: closed database
I 2022/09/28 12:36:38 conf.go:616: cleared workspace temp
I 2022/09/28 12:36:56 working.go:111: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2022/09/28 12:36:56 runtime.go:47: kernel is booting:
    * ver [2.2.2]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [/opt/siyuan]
    * read only [false]
    * container [docker]
    * database [ver=20220501]
    * workspace directory [/siyuan/workspace/, data 20 kB]
I 2022/09/28 12:36:56 serve.go:79: kernel is booting [http://0.0.0.0:6806]
I 2022/09/28 12:36:56 conf.go:559: database size [74 kB], tree/block count [0/0]
I 2022/09/28 12:36:56 working.go:151: kernel booted
I 2022/09/28 12:42:07 index.go:185: rebuilt database for notebook [20210808180117-6v0mkxr] in [0.38s], tree [count=47, size=900 kB]
I 2022/09/28 12:42:07 index.go:323: resolved refs [77] in [89ms]

### 更多信息 More information

桌面环境： i3
docker 命令： `sudo docker run --name siyuan -v $HOME/siyuan/workspace:/siyuan/workspace -p 6806:6806 -u $(id -u):$(id -g) b3log/siyuan --workspace=/siyuan/workspace/`

**Comment by 88250** [comment] 2022-09-28 06:18
Duplicate of  https://github.com/siyuan-note/siyuan/issues/5986

**Closed by 88250** 2022-09-28 06:18 UTC
