### ISSUE TITLE
2.8.0 版本安装后，退出有错误弹窗

### ISSUE THREAD

**Issue by sumengmsm** [siyuan-note/siyuan#7741] opened 2023-03-21 13:12 UTC
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

- 新版安装后，打开后退出会弹出错误窗口。
- 能百分百复现。
- 之前版本并未出现过。

### 期待的结果 Expected result

希望找出原因并修复，希望思源越来越好。

### 截屏或者录屏演示 Screenshot or screen recording presentation

![SiYuan_1ocrdLahdx](https://user-images.githubusercontent.com/62458709/226615387-c8f808c4-e14d-4cca-8b4c-b47e27fe6f8b.png)

### 版本环境 Version environment

```markdown
- Version: 2.8.0
- Operating System: Windows 11 家庭中文版
- Browser (if used): Edge 111.0.1661.44 (正式版本) (64 位)
```

### 日志文件 Log file

      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2023/03/21 21:06:34 runtime.go:52: kernel is booting:
    * ver [2.8.0]
    * arch [amd64]
    * os [Microsoft Windows 11 Home China 10.0.22621.1344 Build 22621.1344]
    * pid [10692]
    * runtime mode [prod]
    * working directory [D:\Soft\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [D:\文档\SiYuan]
I 2023/03/21 21:06:34 conf.go:348: user has disabled [Google Analytics]
I 2023/03/21 21:06:34 runtime.go:98: use network proxy [system]
I 2023/03/21 21:06:34 serve.go:108: kernel [pid=10692] http server [0.0.0.0:13874] is booting
I 2023/03/21 21:06:34 working.go:395: built-in pandoc [ver=3.1.1, bin=D:\文档\SiYuan\temp\pandoc\bin\pandoc.exe]
I 2023/03/21 21:06:35 blocktree.go:386: read block tree [796 kB] to [D:\文档\SiYuan\temp\blocktree], elapsed [0.01s]
I 2023/03/21 21:06:35 conf.go:654: database size [9.7 MB], tree/block count [56/3034]
I 2023/03/21 21:06:35 working.go:159: kernel booted
I 2023/03/21 21:06:35 box.go:74: auto stat [trees=56, blocks=3034, dataSize=3.7 MB, assetsSize=2.0 MB]
I 2023/03/21 21:06:35 disk.go:33: disk usage [total=382 GB, used=144 GB, free=238 GB]
I 2023/03/21 21:06:35 index.go:132: rebuilt database for notebook [20210808180117-czj9bvb] in [0.23s], tree [count=54, size=1.1 MB]
I 2023/03/21 21:06:36 serve.go:121: reverse proxy server [0.0.0.0:6806] is booting
I 2023/03/21 21:07:11 conf.go:429: exiting kernel [force=false, execInstallPkg=0]
I 2023/03/21 21:07:11 database.go:1127: closed database
I 2023/03/21 21:07:11 conf.go:801: cleared workspace temp
I 2023/03/21 21:07:11 conf.go:476: exited kernel

**Comment by 88250** [comment] 2023-03-22 00:42
Duplicate of https://github.com/siyuan-note/siyuan/issues/7736

**Closed by 88250** 2023-03-22 00:42 UTC
