### ISSUE TITLE
2.7.6 无法将标题块转化为文档块

### ISSUE THREAD

**Issue by fwzuw** [siyuan-note/siyuan#7446] opened 2023-02-22 05:17 UTC
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

2.7.6 不行，2.7.5 可以

### 期待的结果 Expected result

修好

### 版本环境 Version environment

```markdown
- Version: 
- Operating System: win10 22h2
- Browser (if used):
```

### 日志文件 Log file

I 2023/02/22 13:14:15 working.go:119: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2023/02/22 13:14:15 runtime.go:57: kernel is booting:
    * ver [2.7.6]
    * arch [amd64]
    * os [Microsoft Windows 10 Pro for Workstations 10.0.19045.2604 Build 19045.2604]
    * pid [69216]
    * runtime mode [prod]
    * working directory [C:\Program Files\WindowsApps\89C2A984.SiYuan_2.7.6.0_x64__1qfd3tsw4ngc2\app\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [D:\工作与学习\思源]
I 2023/02/22 13:14:15 conf.go:236: using Microsoft Store edition
I 2023/02/22 13:14:15 runtime.go:103: use network proxy [system]
I 2023/02/22 13:14:15 serve.go:108: kernel [pid=69216] http server [127.0.0.1:60635] is booting
I 2023/02/22 13:14:15 working.go:396: built-in pandoc [ver=2.19.2, bin=D:\工作与学习\思源\temp\pandoc\bin\pandoc.exe]
I 2023/02/22 13:14:15 blocktree.go:386: read block tree [785 kB] to [D:\工作与学习\思源\temp\blocktree], elapsed [0.01s]
I 2023/02/22 13:14:15 conf.go:626: database size [7.0 MB], tree/block count [136/2770]
I 2023/02/22 13:14:15 working.go:157: kernel booted
I 2023/02/22 13:14:15 box.go:75: auto stat [trees=136, blocks=2770, dataSize=5.5 MB, assetsSize=4.1 MB]
I 2023/02/22 13:14:15 disk.go:33: disk usage [total=4.0 TB, used=3.5 TB, free=544 GB]
I 2023/02/22 13:14:17 serve.go:121: reverse proxy server [127.0.0.1:6806] is booting
I 2023/02/22 13:14:43 conf.go:407: exiting kernel [force=false, execInstallPkg=0]
I 2023/02/22 13:14:43 database.go:1127: closed database
I 2023/02/22 13:14:43 conf.go:773: cleared workspace temp

**Comment by 88250** [comment] 2023-02-22 06:20
Duplicate of https://github.com/siyuan-note/siyuan/issues/7430

**Closed by 88250** 2023-02-22 06:20 UTC
