### ISSUE TITLE
Line break happens inside inline code

### ISSUE THREAD

**Issue by ahinterl** [siyuan-note/siyuan#13146] opened 2024-11-14 08:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Unwanted line breaks may appear for example inside inline code.
![Siyuan screenshot 1](https://github.com/user-attachments/assets/d2b95364-92c3-4aed-9dd2-40cf813ff02b)

### Expected result

Feature to suppress line breaks for inline code in the form of a toggle switch (should be configurable for individual code blocks), or a general feature to suppress line breaks for a sequence of characters (a visual marker is needed to indicate the feature to be active when applied).

### Version environment

```markdown
- Siyuan version: 3.1.11
- Operating system: Windows 11 23H2 22631.4317
- DPI scaling factor: 120 %
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/17745874/siyuan.log)

**Comment by 88250** [comment] 2024-11-14 09:04
Duplicate of https://github.com/siyuan-note/siyuan/issues/8104

**Closed by 88250** 2024-11-14 09:04 UTC

**Comment by TCOTC** [comment] 2024-11-14 10:19
Duplicate of #11248
