### ISSUE TITLE
目录树文档个数提示不会实时更新，只有刷新页面时才更新

### ISSUE THREAD

**Issue by wish5115** [siyuan-note/siyuan#12557] opened 2024-09-23 01:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

目录树文档个数不会实时更新，只有刷新页面才更新，如下图，比如目录aaa新增了文档或删除了文档，提示弹窗显示的还是加载时的旧数据。

<img width="442" alt="image" src="https://github.com/user-attachments/assets/69cfe71d-6a71-4108-a90d-7e5763c7a97c">

### Expected result

目录新增或删除文档后，提示弹窗的文档数能实时更新。

### Version environment

```markdown
- Version: 3.1.6
- Operating System: MacOS 14.6.1
- Browser (if used): 无
```

### Log file

无

**Comment by 88250** [comment] 2024-09-23 01:36
Duplicate of https://github.com/siyuan-note/siyuan/issues/11043

**Closed by 88250** 2024-09-23 01:36 UTC
