### ISSUE TITLE
功能请求：数据库添加对齐选项

### ISSUE THREAD

**Issue by SaXz2** [siyuan-note/siyuan#12630] opened 2024-09-27 18:40 UTC
### In what scenarios do you need this feature?

![image](https://github.com/user-attachments/assets/8d5af922-3320-4a89-81b1-3de74befb5ff)

### Describe the optimal solution

添加数据库列对齐工具

**Comment by TCOTC** [comment] 2024-09-28 01:08
Duplicate of #9859

**Closed** 2024-09-28 03:10 UTC
