### ISSUE TITLE
Ctrl+X will cut the whole paragraph even though I select in one paragraph

### ISSUE THREAD

**Issue by dream-tentacle** [siyuan-note/siyuan#9332] opened 2023-10-02 15:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

段内选中文本，Ctrl+X却会剪切一整段。可复现，一直如此。

### Expected result

希望可以修复该bug

### Version environment

```markdown
- Version: 2.107
- Operating System: win
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/12784159/siyuan.log)

**Comment by 88250** [comment] 2023-10-03 00:54
Duplicate of https://github.com/siyuan-note/siyuan/issues/9283

**Closed by 88250** 2023-10-03 00:54 UTC
