### ISSUE TITLE
700张闪卡时，闪卡速度变慢

### ISSUE THREAD

**Issue by meteor199** [siyuan-note/siyuan#11957] opened 2024-07-12 05:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

700张闪卡时
- 按 Alt +0 打开间隔重复，需要15秒左右。
- 复习时，点击按键也需15秒左右。

![image](https://github.com/user-attachments/assets/7b92ba04-55b9-4a12-879f-e04eb17c0aaa)

升级到3.1.0后，速度变慢了。之前是正常的。
手机端也变慢了。

### Expected result

优化速度

### Version environment

```markdown
- Version: 3.1.0
- Operating System: win 11 pro 64位 23H2
- Browser (if used):
```

### Log file

[siyuan.zip](https://github.com/user-attachments/files/16189033/siyuan.zip)

### More information

- 关闭所有插件和主题、挂件 都不行 。

- 关闭笔记本，只留一个笔记本（闪卡总数23），速度恢复正常了。但是 再重新打开其他笔记本（闪卡总数700+），又变慢了。

**Comment by TCOTC** [comment] 2024-07-12 05:47
Duplicate of #11927 ，请下个版本再试

**Closed** 2024-07-12 05:49 UTC
