### ISSUE TITLE
iPadOS 17.4.1 app卡在logo界面无响应

### ISSUE THREAD

**Issue by DeathofBrain** [siyuan-note/siyuan#11267] opened 2024-05-06 03:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

升级app后会一直卡在logo界面，app版本为最新，iPadOS版本为17.4.1

### Expected result

能打开

### Version environment

```markdown
- Version: v3.0.12
- Operating System: iPadOS 17.4.1
- Browser (if used):
```

### Log file

idk how to get log file in ios :(

**Comment by TCOTC** [comment] 2024-05-06 03:26
Duplicate of #11195

**Closed** 2024-05-06 03:36 UTC
