### ISSUE TITLE
Nested files get deleted without user interference and does not show up in data history

### ISSUE THREAD

**Issue by siysuy** [siyuan-note/siyuan#9551] opened 2023-10-29 09:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

As mentioned in the title: I have many nested files and since the last few updates I continuously have this issue and am forced to revert to backup. 

My most upper parent file remains but all child (nested) files get deleted. 
I do not press anything. This happened more then once and rules out pressing anything. 
In data history I cannot find the removed child files. 

The following is a **guess**: Yesterday before starting to work, I made a snapshot and carefully made sure the nested files were present, but, upon reverting to snapshot the same files were not present there

Additional issue: Some file names are renamed to "Untitled" without user intervention. I noticed that by reverting to a backup.

### Expected result

No files should be deleted without interaction.

### Screenshot or screen recording presentation

![Screenshot_2023-10-29_05-07-59](https://github.com/siyuan-note/siyuan/assets/149296071/8443245c-58e1-4047-b9c0-02e48742e7ed)

### Version environment

```markdown
- Version: v2.10.10
- Operating System: Android, linux
- Browser (if used): Brave, firefox
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/13197727/siyuan.log)

### More information

Upon checking again many nested files were deleted randomly all over the place, so not just in folder 2 but also in folder 3. Basically I am scared that I will lose many notes, hard work and time. Since my database is on the larger side, i fear I can not keep track of which files were deleted randomly. :(

**Comment by 88250** [comment] 2023-10-29 09:33
Hello, have you used data synchronization?

Please upload system logs on desktop and Android (Android logs are exported in About on the right panel).

**Comment by siysuy** [comment] 2023-10-29 09:48
> Hello, have you used data synchronization?
> 
> Please upload system logs on desktop and Android (Android logs are exported in About on the right panel).

Using the instructions i uploaded the siyuan.log file

**Comment by siysuy** [comment] 2023-10-29 09:52
Upon checking again many nested files were deleted randomly all over the place, so not just in folder 2 but also in folder 3

**Comment by siysuy** [comment] 2023-10-29 10:05
Question: I see a lock icon (read-only). 
- Would it help if I lock parent folders that I am not currently working on? 
- If I lock a parent will all child files be locked as well?
- If child's are not locked automatically. Can this be a feature to lock every child inside a parent automatically? I could then lock everything that I am not currently working on.

**Comment by 88250** [comment] 2023-10-29 12:24
No exceptions about the file system were found in the Android logs. Have you used some kind of mobile phone cleaning APP?

> Question: I see a lock icon (read-only).

No, locking the document (in read-only mode) does not solve the problem of file loss.

SiYuan itself will not delete files without reason, otherwise, we would receive a lot of similar feedback, so I guess it should be caused by some external changes on the filesystem.

**Comment by siysuy** [comment] 2023-10-29 12:34
> No exceptions about the file system were found in the Android logs. Have you used some kind of mobile phone cleaning APP?
> 
> > Question: I see a lock icon (read-only).
> 
> No, locking the document (in read-only mode) does not solve the problem of file loss.
> 
> SiYuan itself will not delete files without reason, otherwise, we would receive a lot of similar feedback, so I guess it should be caused by some external changes on the filesystem.

This phone has only one single use case. It is my siyuan database for acces from browser. I do not use this phone for anything else. Minimal installed apps. Only siyuan and an OTP app, Keepass, and a VPN. Nothing else. I do not use the phone for calling or other things. There is **no Mobile phone cleaning APP**.

**Comment by 88250** [comment] 2023-10-29 14:05
Try exporting Data and then importing it into a new workspace on the desktop.

**Comment by siysuy** [comment] 2023-10-29 14:29
> Try exporting Data and then importing it into a new workspace on the desktop.

An hour ago i did the following: 
- exported data from android 
- then imported into new workspace on desktop and fixed as many files as I can
- re-imported it to android
- checked again for siyuan updates to make sure. 

Only time will tell if this helped.

I would prefer, especially in large databases, an option to lock all files by default (beyond read-only) and manually unlock only files that we wish to edit, but I will let this feature slide and forget for now.

**Comment by 88250** [comment] 2023-10-29 14:39
Okay, let's continue to observe.

I'll close the issue now. If it happens again, please reply.

PS: Please try to keep the latest version, thank you.

**Closed by 88250** 2023-10-29 14:39 UTC

**Comment by siysuy** [comment] 2023-11-04 09:44
> Okay, let's continue to observe.
> 
> I'll close the issue now. If it happens again, please reply.
> 
> PS: Please try to keep the latest version, thank you.

The issue happened again. A file with more than 50 nested files was missing. I had to revert to a snapshot. Kindly assist and help with this issue.

[siyuan.log](https://github.com/siyuan-note/siyuan/files/13256270/siyuan.log)
