### ISSUE TITLE
在标题上打字，光标总是会突然跑到最前面

### ISSUE THREAD

**Issue by Yuminis98** [siyuan-note/siyuan#6638] opened 2022-11-18 02:01 UTC
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

如录屏，所以，我在标题上打字，光标会突然跑到最前面去。 导致我打的字出现紊乱。

我确定自己没有任何的误触，光标突然就跑到最前面去了。

### 期待的结果 Expected result

光标恢复正常

### 截屏或者录屏演示 Screenshot or screen recording presentation

https://user-images.githubusercontent.com/117956441/202599521-c5080467-8f8b-44a0-9405-2825c87e75c8.mp4

### 版本环境 Version environment

```markdown
- Version: 2.5.0
- Operating System: win
- Browser (if used):
```

### 日志文件 Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/10037084/system-log.zip)

**Comment by 88250** [comment] 2022-11-18 02:03
Duplicate of https://github.com/siyuan-note/siyuan/issues/6594

**Closed by 88250** 2022-11-18 02:03 UTC
