### ISSUE TITLE
关闭思源笔记,弹出错误

### ISSUE THREAD

**Issue by Ruiless** [siyuan-note/siyuan#7780] opened 2023-03-26 02:18 UTC
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

关闭思源笔记客户端,弹出错误

### 期待的结果 Expected result

正常退出

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/21006134/227751568-aed2d186-8a79-4d97-8b57-bb874468f54e.png)

### 版本环境 Version environment

```markdown
- Version: 2.8.0
- Operating System: macos 13.2.1
- Browser (if used):
```

### 日志文件 Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/11070609/system-log.zip)

**Comment by 88250** [comment] 2023-03-26 02:31
Duplicate of https://github.com/siyuan-note/siyuan/issues/7736

**Closed by 88250** 2023-03-26 02:31 UTC
