### ISSUE TITLE
F5 can refresh image modified externally

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#8775] opened 2023-07-18 07:15 UTC
### In what scenarios do you need this feature?

目前电脑客户端用windows图片编辑器编辑思源笔记里的图片，需要文档关闭再打开才会刷新

### Describe the optimal solution

希望按f5就支持刷新图片，优化操作

**Comment by 88250** [comment] 2023-07-18 08:28
Duplicate of https://github.com/siyuan-note/siyuan/issues/5698

**Closed by 88250** 2023-07-18 08:28 UTC
