### ISSUE TITLE
点查看插件示例后直接在思源里打开了网页且无法退出

### ISSUE THREAD

**Issue by heheda123123** [siyuan-note/siyuan#8466] opened 2023-06-06 11:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

更新到2.9.0之后点更新日志里面的查看插件示例，直接在思源里打开了对应的网页，但是没有退出也没有返回按钮
只能强行关进程
![image](https://github.com/siyuan-note/siyuan/assets/97490782/7077e60a-d39f-48fa-a6b6-d1ce6fb4e4b9)

### Expected result

在外部chrome里面弹出网页，没必要直接在思源里面打开网页

### Version environment

```markdown
- Version: 2.9.0
- Operating System: win 11
- Browser (if used):
```

### Log file

不涉及日志，逻辑问题

**Comment by 88250** [comment] 2023-06-06 12:08
Duplicate of https://github.com/siyuan-note/siyuan/issues/8458

**Comment by heheda123123** [comment] 2023-06-06 12:09
抱歉，搜了下，没看到这个英文issue

**Closed by 88250** 2023-06-06 12:08 UTC
