### ISSUE TITLE
集市增加搜索功能

### ISSUE THREAD

**Issue by edward-kyle** [siyuan-note/siyuan#8831] opened 2023-07-26 11:38 UTC
### In what scenarios do you need this feature?

未来的插件和外观一定会很多，先加一个搜索功能吧。

### Describe the optimal solution

集市增加一个搜索框

**Comment by 88250** [comment] 2023-07-26 11:55
Duplicate of https://github.com/siyuan-note/siyuan/issues/8173

**Closed by 88250** 2023-07-26 11:55 UTC
