### ISSUE TITLE
'Duplicate' database row option

### ISSUE THREAD

**Issue by dvsekhvalnov** [siyuan-note/siyuan#12492] opened 2024-09-15 17:11 UTC
### In what scenarios do you need this feature?

Fast way to enter data in database views (filtered or not), would be nice to have 'duplicate' option for database row or potentially multiple rows.

### Describe the optimal solution

Add 'duplicate' option to database row context menu + optionally keyboard shortcut. See attached screenshot.
![image](https://github.com/user-attachments/assets/5031baea-5395-4c38-a425-23f08bcd37d6)

**Comment by TCOTC** [comment] 2024-09-16 00:40
Duplicate of #10850

**Closed** 2024-09-16 01:58 UTC
