### ISSUE TITLE
Allow different width for different page

### ISSUE THREAD

**Issue by amatya-aditya** [siyuan-note/siyuan#10795] opened 2024-03-30 02:37 UTC
### In what scenarios do you need this feature?

I want my database to occupy full width, for which enabling adaptive width works fine. But at the same time, I don't want my article page to be of adaptive width. I prefer my article page to maintain a minimalistic design for comfortable reading, reducing eye strain and unnecessary eye movement.

Notion offers page-specific width options, allowing for either full-width or a more compact layout.

![image](https://github.com/siyuan-note/siyuan/assets/63241408/e1301d95-fa1a-4bbd-8a87-446c48be0842)

### Describe the optimal solution

It would greatly enhance the usability of SiYuan if we could implement a customizable width setting for individual pages. If assigning a specific width isn't feasible, providing a selection of 3-4 width options for each page would still offer valuable flexibility.

**Comment by 88250** [comment] 2024-03-30 02:39
Duplicate of https://github.com/siyuan-note/siyuan/issues/7388

**Closed by 88250** 2024-03-30 02:39 UTC
