### ISSUE TITLE
新版本pdf直接打不开，好难受啊！我要边看pdf边做笔记弄不了

### ISSUE THREAD

**Issue by whitea133** [siyuan-note/siyuan#12833] opened 2024-10-19 03:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

新版本pdf直接打不开，好难受啊！我要边看pdf边做笔记弄不了。快点修一修，就是新版本的问题。前一分钟没更新新版本，pdf还看的好好的，后一分钟不小心点到了更新，想着应该没什么关系，结果直接pdf打不开。醉了。
另一个bug，一旦触发了上面那个pdf的bug之后，就有可能触发点击关闭键，思源笔记却关闭不了的bug，就逆天。。。。。怎么点关闭都关闭不了
然后，我把主题，插件全关了，依然存在问题！！！
快点修，笔记软件配上pdf很好用，别来个那么恶心的bug啊！！！

### Expected result

感觉修bug

### Screenshot or screen recording presentation

![image](https://github.com/user-attachments/assets/080c3ddb-35dc-41e1-af59-add045572e0e)
![image](https://github.com/user-attachments/assets/90fd696e-3eb2-48ce-a8c0-38904e800d63)
![image](https://github.com/user-attachments/assets/90f1b522-8dd3-44bd-bf8c-29231bf04a28)

### Version environment

```markdown
- Version: 3.1.9
- Operating System: win11
- Browser (if used): 用的是软件
```

### Log file

无

### More information

快修
![image](https://github.com/user-attachments/assets/d8fbd536-062c-4306-b830-c22062e4a4e9)

**Comment by TCOTC** [comment] 2024-10-19 03:36
请下载最新的 dev 版看看

**Comment by whitea133** [comment] 2024-10-19 03:37
那之前的笔记怎么办

**Comment by whitea133** [comment] 2024-10-19 03:40
@TCOTC 是，但是重新下载不是会重新安装码，我要重新卸载笔记软件码？

**Comment by TCOTC** [comment] 2024-10-19 03:41
不需要，覆盖安装就行了

**Comment by whitea133** [comment] 2024-10-19 03:42
@TCOTC 选择哪个版本，win11系统的，exe码

**Comment by TCOTC** [comment] 2024-10-19 03:44
对

**Comment by 88250** [comment] 2024-10-19 03:45
Duplicate of https://github.com/siyuan-note/siyuan/issues/12794

**Closed by 88250** 2024-10-19 03:45 UTC

**Comment by whitea133** [comment] 2024-10-19 03:47
@TCOTC 覆盖安装，东西和环境都不会变动是吧？

**Comment by TCOTC** [comment] 2024-10-19 03:47
对
