### ISSUE TITLE
文档开头回车失效

### ISSUE THREAD

**Issue by pisceswb** [siyuan-note/siyuan#11816] opened 2024-06-25 05:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在文档第一行输入任意内容，光标定位到最开始位置，按下回车键，不管用。
https://ld246.com/article/1719278335958

### Expected result

望修复

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
dev5
```

### Log file

1

### More information

1

**Comment by TCOTC** [comment] 2024-06-25 05:38
Duplicate of #11818

**Closed** 2024-06-25 05:42 UTC
