### ISSUE TITLE
⚠️ 内核因未知原因退出 The kernel exited for unknown reasons

### ISSUE THREAD

**Issue by jsenin** [siyuan-note/siyuan#11441] opened 2024-05-17 09:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Releases before siyuan-3.0.11-linux.AppImage are failing on start. Tested with 3.0.12, 3.0.13, 3.0.14

![imagen](https://github.com/siyuan-note/siyuan/assets/1436451/dc84b0ae-b83e-4769-b63a-23cb83b6c12f)
![imagen](https://github.com/siyuan-note/siyuan/assets/1436451/c6d8986e-aa37-4c25-bf9b-e04364e7de27)

### Expected result

App starts

### Version environment

```markdown
- Version: 3.0.12
- Operating System: Debian GNU/Linux 11 (bullseye)
- Browser (if used):
```

### Log file

```
./siyuan-3.0.12-linux.AppImage 
app is packaged [true], command line args [/tmp/.mount_siyuanu0PVcu/siyuan]
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

got kernel port [45531]
ui version [3.0.12], booting kernel [/tmp/.mount_siyuanu0PVcu/resources/kernel/SiYuan-Kernel --port 45531 --wd /tmp/.mount_siyuanu0PVcu/resources --workspace /home/jorge/Documents --lang en_US]
booted kernel process [pid=2376259, port=45531]
checking kernel version
kernel [pid=2376259, port=45531] exited with code [1]
get kernel version failed: net::ERR_CONNECTION_REFUSED
get kernel version failed: net::ERR_CONNECTION_REFUSED
get kernel version failed: net::ERR_CONNECTION_REFUSED
get kernel version failed: net::ERR_CONNECTION_REFUSED
get kernel version failed: net::ERR_CONNECTION_REFUSED
get kernel version failed: net::ERR_CONNECTION_REFUSED
get kernel version failed: net::ERR_CONNECTION_REFUSED
get kernel version failed: net::ERR_CONNECTION_REFUSED
get kernel version failed: net::ERR_CONNECTION_REFUSED
get kernel version failed: net::ERR_CONNECTION_REFUSED
get kernel version failed: net::ERR_CONNECTION_REFUSED
get kernel version failed: net::ERR_CONNECTION_REFUSED
get kernel version failed: net::ERR_CONNECTION_REFUSED
get kernel version failed: net::ERR_CONNECTION_REFUSED
get kernel version failed: net::ERR_CONNECTION_REFUSED
get kernel ver failed
```

**Comment by 88250** [comment] 2024-05-17 09:20
Duplicate of https://github.com/siyuan-note/siyuan/issues/11417

**Closed by 88250** 2024-05-17 09:20 UTC
