### ISSUE TITLE
docker 更新后账号界面无法显示， 没办法登录账号

### ISSUE THREAD

**Issue by jhzerone** [siyuan-note/siyuan#10245] opened 2024-01-24 08:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

docker 今天的更新到2.12.4后， 账号页面显示不出来了， 无法登录账号

### Expected result

能显示页面， 登录账号

### Version environment

```markdown
- Version: v2.12.4
- Operating System: docker
- Browser (if used): edge
```

### Log file

cannot unmarshal string into Go struct field Funding.funding.custom of type []string 不知这个是否有影响

**Comment by 88250** [comment] 2024-01-24 08:57
Duplicate of https://github.com/siyuan-note/siyuan/issues/10238

**Closed by 88250** 2024-01-24 08:57 UTC
