### ISSUE TITLE
从反链面板复制列表出现bug

### ISSUE THREAD

**Issue by Oltermare** [siyuan-note/siyuan#6558] opened 2022-11-12 02:26 UTC
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

![反链bug](https://user-images.githubusercontent.com/64324088/201452030-7179973d-0df3-4bcc-9db1-eedc118b91d2.gif)

只要是复制：反链面板当前显示的完整列表，就会出现这个bug，无论在原文档是不是子项

### 期待的结果 Expected result

应当可以正常复制

### 版本环境 Version environment

```markdown
- Version: 2.4.12
- Operating System: win10
- Browser (if used):
```

### 日志文件 Log file

[log.txt](https://github.com/siyuan-note/siyuan/files/9993887/log.txt)
当天进行了升级，重启之后依然有这个问题

**Comment by 88250** [comment] 2022-11-12 02:34
Duplicate of https://github.com/siyuan-note/siyuan/issues/6555

**Closed by 88250** 2022-11-12 02:34 UTC
