### ISSUE TITLE
Block reference should not show the comments of original block

### ISSUE THREAD

**Issue by XinLi0111** [siyuan-note/siyuan#9278] opened 2023-09-26 13:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/31495943/cd5f9c00-5e6c-47ea-a107-330ba829083f)

### Expected result

just show the main text, excluding the comments

### Version environment

```markdown
- Version: 2.10.7
- Operating System: win11
- Browser (if used):
```

### Log file

-

**Comment by 88250** [comment] 2023-09-27 02:25
![image](https://github.com/siyuan-note/siyuan/assets/873584/1c42715d-cb35-4cce-98fa-423a99bbfa54)


Please check it under the default theme and close all plugins.

I will close this issue first. If the issue can still be reproduced after defaulting to the default theme and closing plugins and other extensions, please tell me, thank you.

**Closed by 88250** 2023-09-27 02:25 UTC

**Comment by XinLi0111** [comment] 2023-09-28 03:31
![image](https://github.com/siyuan-note/siyuan/assets/31495943/fcc3c464-8b7e-48e1-99bf-bc1dc42912a7)
![image](https://github.com/siyuan-note/siyuan/assets/31495943/6c00cedf-0fe1-4b24-9237-6378377411bf)

it appears on defualt theme, too.

**Comment by 88250** [comment] 2023-09-28 03:53
Oh, I understand, this is by design, because the memo content must support search, so it can only appear in the anchor text, unless static anchor text is used to avoid this problem.
