### ISSUE TITLE
siyuan-3.1.18-win版本，软换行失效（shift+enter）

### ISSUE THREAD

**Issue by Mctalos** [siyuan-note/siyuan#13690] opened 2024-12-31 15:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

siyuan-3.1.18-win版本，软换行失效（shift+enter）。回退siyuan-3.1.17-win正常。

### Expected result

shift+enter软换行

### Version environment

```markdown
siyuan-3.1.18-win
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/18282488/siyuan.log)

**Comment by 88250** [comment] 2024-12-31 15:50
Duplicate of https://github.com/siyuan-note/siyuan/issues/13683

**Closed by 88250** 2024-12-31 15:50 UTC
