### ISSUE TITLE
一个小问题：数字+中文句号，不能再打出有序列表

### ISSUE THREAD

**Issue by zhoutaosheng** [siyuan-note/siyuan#13639] opened 2024-12-27 01:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

比如 1。 不能再打出来有序列表
之前的版本中，可以

### Expected result

这在中文输入中，还是挺方便的，希望保留这类

### Version environment

```markdown
- Version: 3.1.17
- Operating System: Win11
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment] 2024-12-27 01:36
Duplicate of https://github.com/siyuan-note/siyuan/issues/13528

**Closed by 88250** 2024-12-27 01:36 UTC
