### ISSUE TITLE
When typing symbols, the mouse cursor returns to the beginning of the line.

### ISSUE THREAD

**Issue by taozina** [siyuan-note/siyuan#5193] opened 2022-06-15 13:57 UTC
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

When typing a word that contains symbols ( #, $, %, ~, ´ ) in the title of a document, the mouse cursor returns to the beginning of the line. Therefore, we were unable to type correctly.

### 期待的结果 Expected result

The mouse cursor proceeds correctly as you type.

### 版本环境 Version environment

```markdown
- Version: 2.0.20
- Operating System: Windows 10
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/8909961/siyuan.log)

**Comment by 88250** [comment] 2022-06-16 02:01
I can't reproduce it.

![issue](https://user-images.githubusercontent.com/873584/173975057-eac4c0ae-6994-481e-be24-0b485ccc658a.gif)

**Comment by 88250** [comment] 2022-06-16 12:23
It can be reproduced. It is a bug caused by the trailing space. It will be fixed in https://github.com/siyuan-note/siyuan/issues/5202, thank you.

**Closed by 88250** 2022-06-16 12:23 UTC

**Comment by taozina** [comment] 2022-06-16 23:52
![aaaaaa](https://user-images.githubusercontent.com/90691302/174196379-e56bd22c-2fce-43c4-9913-37b049475120.gif)

**Comment by taozina** [comment] 2022-06-17 12:50
@88250  version 2.0.21 fixed this bug. SiYuan is 100% work. Thanks.
