### ISSUE TITLE
Clicking link of fixed issues in changelog open a full screen browser window

### ISSUE THREAD

**Issue by ttimasdf** [siyuan-note/siyuan#8495] opened 2023-06-08 12:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Every time the first launch after an upgrade, there's a pop up window with fixed issues and improvements. the links are clickable and the main window jumps to Github. which cannot navigate back to the note view.

The close button is missing and right-clicking to close the window on the taskbar does not work, and neither does Alt-F4.

### Expected result

The link should open in an external browser, or at least Alt-F4 should work.

### Version environment

```markdown
- Version: v2.9.0
- Operating System: Windows
- Browser (if used):
```

### Log file

No log content significantly related to this issue.

**Comment by 88250** [comment] 2023-06-08 12:43
Duplicate of https://github.com/siyuan-note/siyuan/issues/8458

**Closed by 88250** 2023-06-08 12:43 UTC
