### ISSUE TITLE
Make 'Enter text' in the template optional

### ISSUE THREAD

**Issue by MindArchr** [siyuan-note/siyuan#8254] opened 2023-05-14 20:21 UTC
### In what scenarios do you need this feature?

Make the 'Enter text' optional in the document template. Having this as a mandatory function makes it look like actual wording integrated in my document, and it now looks cluttered and confusing. I would downgrade to the version before this was implemented if I could. 

### Describe the optimal solution

Please make this optional in the settings as to whether the user needs this guideline or not

### Describe the candidate solution

The removal of it completely or an option for the user

**Comment by 88250** [comment] 2023-05-15 01:53
Duplicate of https://github.com/siyuan-note/siyuan/issues/8232

**Closed by 88250** 2023-05-15 01:53 UTC
