### ISSUE TITLE
2.0.17版本导出笔记功能失效

### ISSUE THREAD

**Issue by zbluex** [siyuan-note/siyuan#5129] opened 2022-06-08 07:33 UTC
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

在v2.0.17版本中，通过导出markdown、sy.zip等方式，弹出新的空白窗口，之后再无动作

### 期待的结果 Expected result

下载导出内容

### 版本环境 Version environment

```markdown
- Version: v2.0.17 Docker
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

3493 I 2022/06/08 15:24:02 conf.go:174: using network proxy [http://10.28.23.69:8087]
3494 I 2022/06/08 15:24:02 serve.go:78: kernel is booting [http://0.0.0.0:6806]
3495 W 2022/06/08 15:24:05 blocktree.go:257: read block tree [889 kB] to [/home/siyuan/Documents/SiYuan/temp/blocktree.msgpack], elapsed [2.67s]
3496 I 2022/06/08 15:24:05 conf.go:512: database size [15 MB], block count [3219]
3497 I 2022/06/08 15:24:05 working.go:137: kernel booted
3498 E 2022/06/08 15:25:24 export.go:467: not found block [ea4f4c99-ba36-4a9e-9ae2-6c4053b92976]
3499 E 2022/06/08 15:26:37 export.go:467: not found block [fe2e4467-55c2-477c-8c22-b4e735f6a52b]
3500 E 2022/06/08 15:27:05 export.go:467: not found block [ccbc5b4e-7ab2-438a-a143-82a116044af0]
3501 E 2022/06/08 15:27:08 liandi.go:322: get community user failed: Post "https://siyuan-sync.b3logfile.com/apis/siyuan/user": x509: certificate signed by unknown authority
3502 E 2022/06/08 15:27:13 export.go:467: not found block [eee7356c-d3e4-478e-8e44-17b19f9fbb6f]
3503 E 2022/06/08 15:27:37 rhy.go:43: get version meta info failed: Get "https://siyuan-sync.b3logfile.com/apis/siyuan/version?ver=2.0.17": x509: certificate signed by unknown authority
3504 E 2022/06/08 15:28:23 osssync.go:48: get cloud space failed: Post "https://siyuan-sync.b3logfile.com/apis/siyuan/data/getSiYuanWorkspace": x509: certificate signed by unknown authority
3505 E 2022/06/08 15:28:27 export.go:467: not found block [afcc4fcb-62e7-4f01-a04f-f118b1d832f8]
3506 E 2022/06/08 15:29:33 export.go:467: not found block [6fa843d8-d20e-4e04-91ed-e82047fb1e83]
3507 E 2022/06/08 15:29:39 export.go:52: not found block [27f41501-40a4-4e48-bf0a-bae7ef040291]

**Comment by 88250** [comment] 2022-06-08 09:28
Duplicate of https://github.com/siyuan-note/siyuan/issues/5120

**Closed by 88250** 2022-06-08 09:28 UTC
