### ISSUE TITLE
内核因未知原因退出 The kernel exited for unknown reasons

### ISSUE THREAD

**Issue by psyuhen** [siyuan-note/siyuan#7829] opened 2023-03-30 02:32 UTC
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

自动崩溃

### 期待的结果 Expected result

期待修复 

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/6522440/228712920-6f873d1a-5d3e-4cb8-bc34-06ff03784edb.png)

### 版本环境 Version environment

```markdown
- Version: 2.8.1
- Operating System: windows 11
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/11107171/siyuan.log)

### 更多信息 More information

![image](https://user-images.githubusercontent.com/6522440/228712865-1c24fb06-330b-4f52-b2c8-55d5ca7e3ef2.png)

**Comment by 88250** [comment] 2023-03-30 02:34
Duplicate of https://github.com/siyuan-note/siyuan/issues/7806

**Closed by 88250** 2023-03-30 02:34 UTC
