### ISSUE TITLE
scrollbar not working

### ISSUE THREAD

**Issue by taozina0587** [siyuan-note/siyuan#6595] opened 2022-11-15 10:37 UTC
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

scrollbar not working. On all notebooks I can't scroll down the page with the mouse pointer. I can only scroll down using the mouse scroll itself

### 期待的结果 Expected result

scroll down the page with the mouse pointer.

### 版本环境 Version environment

```markdown
- Version: 2.5.0
- Operating System: Linux
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/10011778/siyuan.log)

**Comment by woniuxia** [comment] 2022-11-15 11:55
https://github.com/siyuan-note/siyuan/issues/6588
Fix in next version。

**Comment by 88250** [comment] 2022-11-15 12:27
Duplicate of https://github.com/siyuan-note/siyuan/issues/6588

**Closed by 88250** 2022-11-15 12:27 UTC
