### ISSUE TITLE
提及关键词不会被高亮

### ISSUE THREAD

**Issue by tcmtom** [siyuan-note/siyuan#13328] opened 2024-12-02 01:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

https://ld246.com/article/1732166234911
已在默认主题下测试

### Expected result

提及可以被高亮

### Version environment

```markdown
- Version: 微软应用商店3.1.13
- Operating System: win11
- Browser (if used):
```

### Log file

——

**Comment by 88250** [comment] 2024-12-02 01:17
Duplicate of https://github.com/siyuan-note/siyuan/issues/13324

**Comment by 88250** [comment] 2024-12-13 02:40
下个版本解决，感谢反馈。

**Closed** 2024-12-13 02:48 UTC
