### ISSUE TITLE
无法将内容粘贴（ctrl+v）到数据库标题中

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#13674] opened 2024-12-30 12:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

<img width="326" alt="20241230_205653_888_copy" src="https://github.com/user-attachments/assets/bd9639aa-d67a-4c7d-9771-06e3118f192a" />

### Expected result

。。

### Version environment

```markdown
- Version: 最新
- Operating System: win11
- Browser (if used):
```

### Log file

。。

**Comment by 88250** [comment] 2024-12-30 13:04
我这里测试正常，请检查是否是插件或者代码片段影响。

**Comment by TCOTC** [comment] 2024-12-30 13:25
Duplicate of #13607

**Comment by 88250** [comment] 2024-12-30 13:26
哦哦，那我关闭了。

**Closed by 88250** 2024-12-30 13:26 UTC
