### ISSUE TITLE
希望添加文档树多选功能

### ISSUE THREAD

**Issue by SaXz2** [siyuan-note/siyuan#12885] opened 2024-10-23 15:38 UTC
### In what scenarios do you need this feature?

现在只能按住Ctrl来一个一个点击我笔记写的优点多了想移动一下位置操作太过于繁琐了
![Clip_2024-10-23_23-37-43](https://github.com/user-attachments/assets/afca752f-2c52-4002-a639-eabbfd244301)

### Describe the optimal solution

希望改成框选或者是按照按住 Shift 选中两个文件之间的范围

**Comment by 88250** [comment] 2024-10-23 15:48
Duplicate of https://github.com/siyuan-note/siyuan/issues/12185

**Closed by 88250** 2024-10-23 15:48 UTC
